force-app/main/default/objects/Call_Log__c/Call_Log__c.object-meta.xml
<CustomObject>
    <label>Call Log</label>
    <nameField>
        <displayFormat>Call Log - {0000}</displayFormat>
        <label>Call Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Log__c/fields/Course_Enrolled__c.field-meta.xml
<CustomField>
    <fullName>Course_Enrolled__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Enrolled</label>
    <referenceTo>Course_Enrolled__c</referenceTo>
    <relationshipLabel>Call Logs</relationshipLabel>
    <relationshipName>Call_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Log__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Call Logs</relationshipLabel>
    <relationshipName>Call_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Log__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <label>Phone Number (Customer)</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Call_Log__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>M_Stages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Enrolled__c/Course_Enrolled__c.object-meta.xml
<CustomObject>
    <label>Course Enrolled</label>
    <nameField>
        <label>Student Enrolled Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Enrolleds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Enrolled__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>City</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Enrolled__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Course</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Enrolled__c/fields/Stages__c.field-meta.xml
<CustomField>
    <fullName>Stages__c</fullName>
    <label>Stages</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>stages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Enrolled__c/recordTypes/CMA.recordType-meta.xml
<RecordType>
    <fullName>CMA</fullName>
    <active>true</active>
    <label>CMA</label>
</RecordType>

force-app/main/default/objects/Email__c/Email__c.object-meta.xml
<CustomObject>
    <label>Email</label>
    <nameField>
        <displayFormat>Email - {0000}</displayFormat>
        <label>Email Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Email__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Emails</relationshipLabel>
    <relationshipName>Emails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Course</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phone Number</label>
    <referenceTo>Phone_Number__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/CAN_ID__c.field-meta.xml
<CustomField>
    <fullName>CAN_ID__c</fullName>
    <formula>Candidate__r.Candidate_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CAN ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Course</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Is_ReEnquiry__c.field-meta.xml
<CustomField>
    <fullName>Is_ReEnquiry__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is ReEnquiry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>M_Stages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/recordTypes/CMA.recordType-meta.xml
<RecordType>
    <fullName>CMA</fullName>
    <active>true</active>
    <label>CMA</label>
</RecordType>

force-app/main/default/objects/Phone_Number__c/Phone_Number__c.object-meta.xml
<CustomObject>
    <label>Phone Number</label>
    <nameField>
        <displayFormat>Phone - {0000}</displayFormat>
        <label>Phone Number Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Phone Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Phone_Number__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Phone Numbers</relationshipLabel>
    <relationshipName>Phone_Numbers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/City.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Ahmedabad</fullName>
    </customValue>
    <customValue>
        <fullName>Bangalore</fullName>
    </customValue>
    <customValue>
        <fullName>Chennai</fullName>
    </customValue>
    <customValue>
        <fullName>Delhi</fullName>
    </customValue>
    <customValue>
        <fullName>Dubai</fullName>
    </customValue>
    <customValue>
        <fullName>Ernakulam</fullName>
    </customValue>
    <customValue>
        <fullName>Hyderabad</fullName>
    </customValue>
    <customValue>
        <fullName>Kolkata</fullName>
    </customValue>
    <customValue>
        <fullName>Mumbai</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Pune</fullName>
    </customValue>
    <masterLabel>City</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Course.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CMA</fullName>
    </customValue>
    <customValue>
        <fullName>CPA</fullName>
    </customValue>
    <customValue>
        <fullName>CAIRA</fullName>
    </customValue>
    <customValue>
        <fullName>MCOM</fullName>
    </customValue>
    <customValue>
        <fullName>US Pathway</fullName>
    </customValue>
    <masterLabel>Course</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/M_Stages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>M1</fullName>
    </customValue>
    <customValue>
        <fullName>M2</fullName>
    </customValue>
    <customValue>
        <fullName>M3</fullName>
    </customValue>
    <customValue>
        <fullName>M3+</fullName>
    </customValue>
    <customValue>
        <fullName>M3++</fullName>
    </customValue>
    <customValue>
        <fullName>M4-</fullName>
    </customValue>
    <customValue>
        <fullName>M4</fullName>
    </customValue>
    <customValue>
        <fullName>M5</fullName>
    </customValue>
    <customValue>
        <fullName>M6</fullName>
    </customValue>
    <customValue>
        <fullName>M7</fullName>
    </customValue>
    <customValue>
        <fullName>M7+</fullName>
    </customValue>
    <customValue>
        <fullName>B1</fullName>
    </customValue>
    <customValue>
        <fullName>B2</fullName>
    </customValue>
    <customValue>
        <fullName>B3</fullName>
    </customValue>
    <customValue>
        <fullName>B3+</fullName>
    </customValue>
    <customValue>
        <fullName>B3++</fullName>
    </customValue>
    <customValue>
        <fullName>B4-</fullName>
    </customValue>
    <customValue>
        <fullName>B4</fullName>
    </customValue>
    <customValue>
        <fullName>B5</fullName>
    </customValue>
    <customValue>
        <fullName>B6</fullName>
    </customValue>
    <customValue>
        <fullName>B7</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
    </customValue>
    <customValue>
        <fullName>M7#</fullName>
    </customValue>
    <customValue>
        <fullName>U1</fullName>
    </customValue>
    <customValue>
        <fullName>U2</fullName>
    </customValue>
    <customValue>
        <fullName>U3</fullName>
    </customValue>
    <customValue>
        <fullName>U3+</fullName>
    </customValue>
    <customValue>
        <fullName>U3++</fullName>
    </customValue>
    <customValue>
        <fullName>U4-</fullName>
    </customValue>
    <customValue>
        <fullName>U4</fullName>
    </customValue>
    <masterLabel>M Stages</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/stages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>M7+</fullName>
        <default>true</default>
        <label>M7+</label>
    </customValue>
    <customValue>
        <fullName>M7#</fullName>
    </customValue>
    <customValue>
        <fullName>M7#-</fullName>
    </customValue>
    <customValue>
        <fullName>M7##</fullName>
    </customValue>
    <customValue>
        <fullName>M8</fullName>
    </customValue>
    <customValue>
        <fullName>M9</fullName>
    </customValue>
    <customValue>
        <fullName>M9+</fullName>
    </customValue>
    <customValue>
        <fullName>M10</fullName>
    </customValue>
    <customValue>
        <fullName>M10+</fullName>
    </customValue>
    <customValue>
        <fullName>M11</fullName>
    </customValue>
    <customValue>
        <fullName>M11+</fullName>
    </customValue>
    <customValue>
        <fullName>M11#</fullName>
    </customValue>
    <customValue>
        <fullName>M12</fullName>
    </customValue>
    <customValue>
        <fullName>M13</fullName>
    </customValue>
    <customValue>
        <fullName>M13+</fullName>
    </customValue>
    <customValue>
        <fullName>M13++</fullName>
    </customValue>
    <customValue>
        <fullName>M13#</fullName>
    </customValue>
    <customValue>
        <fullName>M14</fullName>
    </customValue>
    <customValue>
        <fullName>M14+</fullName>
    </customValue>
    <customValue>
        <fullName>M14++</fullName>
    </customValue>
    <customValue>
        <fullName>M14#</fullName>
    </customValue>
    <customValue>
        <fullName>M15</fullName>
    </customValue>
    <customValue>
        <fullName>M15+</fullName>
    </customValue>
    <customValue>
        <fullName>M15++</fullName>
    </customValue>
    <customValue>
        <fullName>M15#</fullName>
    </customValue>
    <customValue>
        <fullName>M16</fullName>
    </customValue>
    <customValue>
        <fullName>M16+</fullName>
    </customValue>
    <customValue>
        <fullName>M16++</fullName>
    </customValue>
    <customValue>
        <fullName>M16#</fullName>
    </customValue>
    <customValue>
        <fullName>M17</fullName>
    </customValue>
    <masterLabel>stages</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RunoCallIdentityServiceTest.cls
@IsTest
public class RunoCallIdentityServiceTest {

    // Helper method to get Lead Record Type Id
    private static Id getLeadRecordTypeId() {
        RecordType rt = [SELECT Id FROM RecordType 
                         WHERE SObjectType='Lead__c' 
                         ORDER BY CreatedDate ASC LIMIT 1];
        return rt.Id;
    }

    // Helper method to get Course_Enrolled Record Type Id
    private static Id getCourseEnrolledRecordTypeId() {
        RecordType rt = [SELECT Id FROM RecordType 
                         WHERE SObjectType='Course_Enrolled__c' 
                         ORDER BY CreatedDate ASC LIMIT 1];
        return rt.Id;
    }

   /* @IsTest
    static void testGetIdentityWithLead() {
        Id leadRtId = getLeadRecordTypeId();

        Lead__c leadRec = new Lead__c(
            Name = 'Test Lead',
            Email__c = 'lead@test.com',
            Phone__c = '1234567890',
            City__c = 'Delhi',
            Is_ReEnquiry__c = true,
            RecordTypeId = leadRtId,
            Course__c = 'CMA',   // exact picklist value
            Stage__c  = 'M1'     // exact picklist value
        );
        insert leadRec;

        Test.startTest();
        RunoCallIdentityService.IdentityDTO dto = 
            RunoCallIdentityService.getIdentity(leadRec.Id);
        Test.stopTest();

        System.assertNotEquals(null, dto, 'DTO should not be null');
        System.assertEquals('Test Lead', dto.name);
        System.assertEquals('lead@test.com', dto.email);
        System.assertEquals('1234567890', dto.phone);
        System.assertEquals('Delhi', dto.city);
        System.assertEquals('CMA', dto.source);
        System.assertEquals('M1', dto.stage);
        System.assertEquals('Yes', dto.mhpTag);
        System.assertEquals(UserInfo.getUserName(), dto.leadOwner);
        System.assertEquals(null, dto.canId, 'CAN_ID__c is read-only, should be null');
    }
*/

  /*  @IsTest
    static void testGetIdentityWithCourseEnrolled() {
        Id ceRtId = getCourseEnrolledRecordTypeId();

        Course_Enrolled__c ceRec = new Course_Enrolled__c(
            Phone__c = '9876543210',
            City__c = 'Mumbai',
            RecordTypeId = ceRtId,
            Course__c = 'CMA',   // exact picklist value
            Stages__c = 'M1'     // exact picklist value
        );
        insert ceRec;

        Test.startTest();
        RunoCallIdentityService.IdentityDTO dto = 
            RunoCallIdentityService.getIdentity(ceRec.Id);
        Test.stopTest();

        System.assertNotEquals(null, dto, 'DTO should not be null');
        System.assertEquals('NA', dto.email);
        System.assertEquals('9876543210', dto.phone);
        System.assertEquals('Mumbai', dto.city);
        System.assertEquals('CMA', dto.source);
        System.assertEquals('M1', dto.stage);
        System.assertEquals(null, dto.canId);
    }
*/
    @IsTest
    static void testGetIdentityWithCallLog() {
        Call_Log__c callRec = new Call_Log__c(
            Customer_Name__c = 'Customer Test',
            Phone_Number__c = '5555555555'
        );
        insert callRec;

        Test.startTest();
        RunoCallIdentityService.IdentityDTO dto = 
            RunoCallIdentityService.getIdentity(callRec.Id);
        Test.stopTest();

        System.assertNotEquals(null, dto, 'DTO should not be null');
        System.assertEquals('Customer Test', dto.name);
        System.assertEquals('NA', dto.email);
        System.assertEquals('5555555555', dto.phone);
        System.assertEquals('NA', dto.city);
        System.assertEquals('NA', dto.source);
        System.assertEquals('NA', dto.stage);
        System.assertEquals(null, dto.canId);
    }

    @IsTest
    static void testGetIdentityWithNullId() {
        Test.startTest();
        RunoCallIdentityService.IdentityDTO dto = 
            RunoCallIdentityService.getIdentity(null);
        Test.stopTest();

        System.assertEquals(null, dto, 'DTO should be null when recordId is null');
    }

  @IsTest
    static void testGetCourseIdentityWrapper() {
        Id leadRtId = getLeadRecordTypeId();

        Lead__c leadRec = new Lead__c(
            Name = 'Wrapper Lead',
            Email__c = 'wrapper@test.com',
            RecordTypeId = leadRtId
        );
        insert leadRec;

        Test.startTest();
        RunoCallIdentityService.IdentityDTO dto = 
            RunoCallIdentityService.getCourseIdentity(leadRec.Id);
        Test.stopTest();

        System.assertNotEquals(null, dto, 'DTO from wrapper should not be null');
        System.assertEquals('Wrapper Lead', dto.name);
        System.assertEquals('wrapper@test.com', dto.email);
    }
}