force-app/main/default/objects/Call_Log__c/Call_Log__c.object-meta.xml
<CustomObject>
    <label>Call Log</label>
    <nameField>
        <displayFormat>Call Log - {0000}</displayFormat>
        <label>Call Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Log__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Call Logs</relationshipLabel>
    <relationshipName>Call_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Log__c/fields/Feedback__c.field-meta.xml
<CustomField>
    <fullName>Feedback__c</fullName>
    <label>Feedback</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Call_Log__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Call Logs</relationshipLabel>
    <relationshipName>Call_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Log__c/fields/Next_Follow_Up_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Follow_Up_Date__c</fullName>
    <label>Next Follow Up Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Call_Log__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <label>Phone Number (Customer)</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Call_Log__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>M_Stages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Log__c/fields/Untracked__c.field-meta.xml
<CustomField>
    <fullName>Untracked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Untracked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Email__c/Email__c.object-meta.xml
<CustomObject>
    <label>Email</label>
    <nameField>
        <displayFormat>Email - {0000}</displayFormat>
        <label>Email Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Email__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Emails</relationshipLabel>
    <relationshipName>Emails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Email__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Emails</relationshipLabel>
    <relationshipName>Emails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Candidate_ID__c.field-meta.xml
<CustomField>
    <fullName>Candidate_ID__c</fullName>
    <label>Candidate ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Course</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phone Number</label>
    <referenceTo>Phone_Number__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Course</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Disable_Round_Robin__c.field-meta.xml
<CustomField>
    <fullName>Disable_Round_Robin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disable Round Robin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Is_DND__c.field-meta.xml
<CustomField>
    <fullName>Is_DND__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is DND</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Is_Spam__c.field-meta.xml
<CustomField>
    <fullName>Is_Spam__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Spam</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Next_Follow_Up_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Follow_Up_Date__c</fullName>
    <label>Next Follow Up Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>M_Stages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/recordTypes/CPA.recordType-meta.xml
<RecordType>
    <fullName>CPA</fullName>
    <active>true</active>
    <label>CPA</label>
</RecordType>

force-app/main/default/objects/Phone_Number__c/Phone_Number__c.object-meta.xml
<CustomObject>
    <label>Phone Number</label>
    <nameField>
        <displayFormat>Phone - {0000}</displayFormat>
        <label>Phone Number Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Phone Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Phone_Number__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Phone Numbers</relationshipLabel>
    <relationshipName>Phone_Numbers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Phone_Number__c/fields/Is_DND__c.field-meta.xml
<CustomField>
    <fullName>Is_DND__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is DND</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Phone_Number__c/fields/Is_Spam__c.field-meta.xml
<CustomField>
    <fullName>Is_Spam__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Spam</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Phone_Number__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Phone Numbers</relationshipLabel>
    <relationshipName>Phone_Numbers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Course.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CMA</fullName>
    </customValue>
    <customValue>
        <fullName>CPA</fullName>
    </customValue>
    <customValue>
        <fullName>CAIRA</fullName>
    </customValue>
    <customValue>
        <fullName>MCOM</fullName>
    </customValue>
    <customValue>
        <fullName>US Pathway</fullName>
    </customValue>
    <masterLabel>Course</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/M_Stages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>M1</fullName>
    </customValue>
    <customValue>
        <fullName>M2</fullName>
    </customValue>
    <customValue>
        <fullName>M3</fullName>
    </customValue>
    <customValue>
        <fullName>M3+</fullName>
    </customValue>
    <customValue>
        <fullName>M3++</fullName>
    </customValue>
    <customValue>
        <fullName>M4-</fullName>
    </customValue>
    <customValue>
        <fullName>M4</fullName>
    </customValue>
    <customValue>
        <fullName>M5</fullName>
    </customValue>
    <customValue>
        <fullName>M6</fullName>
    </customValue>
    <customValue>
        <fullName>M7</fullName>
    </customValue>
    <customValue>
        <fullName>M7+</fullName>
    </customValue>
    <customValue>
        <fullName>B1</fullName>
    </customValue>
    <customValue>
        <fullName>B2</fullName>
    </customValue>
    <customValue>
        <fullName>B3</fullName>
    </customValue>
    <customValue>
        <fullName>B3+</fullName>
    </customValue>
    <customValue>
        <fullName>B3++</fullName>
    </customValue>
    <customValue>
        <fullName>B4-</fullName>
    </customValue>
    <customValue>
        <fullName>B4</fullName>
    </customValue>
    <customValue>
        <fullName>B5</fullName>
    </customValue>
    <customValue>
        <fullName>B6</fullName>
    </customValue>
    <customValue>
        <fullName>B7</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
    </customValue>
    <customValue>
        <fullName>M7#</fullName>
    </customValue>
    <customValue>
        <fullName>U1</fullName>
    </customValue>
    <customValue>
        <fullName>U2</fullName>
    </customValue>
    <customValue>
        <fullName>U3</fullName>
    </customValue>
    <customValue>
        <fullName>U3+</fullName>
    </customValue>
    <customValue>
        <fullName>U3++</fullName>
    </customValue>
    <customValue>
        <fullName>U4-</fullName>
    </customValue>
    <customValue>
        <fullName>U4</fullName>
    </customValue>
    <masterLabel>M Stages</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TagLeadControllerTest.cls
@IsTest
public class TagLeadControllerTest {

    @TestSetup
    static void setupData() {
        Id leadRecTypeId = getLeadRecordTypeId();
        String courseValue = getCourseValueForRecordType(leadRecTypeId);

        Lead standardLead = new Lead(
            LastName = 'Candidate Lead',
            Company = 'CandCo',
            Phone = '2222222222',
            Candidate_ID__c = 'CAND123'
        );
        insert standardLead;

        Lead__c customLead = new Lead__c(
            Name = 'Custom Lead',
            Phone__c = '1111111111',
            Email__c = 'test@abc.com',
            Candidate__c = standardLead.Id,
            Stage__c = 'M3',
            Disable_Round_Robin__c = false
        );
        if (courseValue != null) {
            customLead.Course__c = courseValue;
        }
        if (leadRecTypeId != null) {
            customLead.RecordTypeId = leadRecTypeId;
        }
        insert customLead;

        Call_Log__c callLog = new Call_Log__c(
            Phone_Number__c = '1111111111',
            Feedback__c = 'Initial Feedback',
            Untracked__c = true
        );
        insert callLog;
    }

    @IsTest
    static void testSearchLeadsByNameOrPhone() {
        List<Lead__c> results = TagLeadController.searchLeads('Custom');

        results = TagLeadController.searchLeads('1111111111');

        results = TagLeadController.searchLeads('CAND123');
    }

    @IsTest
    static void testTagOrCreateLead_ExistingLead() {
        Lead__c existingLead = [
            SELECT Id, Candidate__c, Name, Phone__c, Email__c
            FROM Lead__c
            WHERE Name = 'Custom Lead'
            LIMIT 1
        ];
        Call_Log__c callLog = [
            SELECT Id
            FROM Call_Log__c
            WHERE Phone_Number__c = '1111111111'
            LIMIT 1
        ];

        TagLeadController.tagOrCreateLead(
            callLog.Id,
            existingLead.Id,
            existingLead.Name,
            getCourseValueForRecordType(getLeadRecordTypeId()),
            existingLead.Email__c,
            existingLead.Phone__c,
            false,
            'L1',
            'L2',
            'Updated feedback',
            '2026-02-16T10:00',
            getLeadRecordTypeId()
        );

        callLog = [
            SELECT Lead__c, Candidate__c, Feedback__c, Untracked__c, Next_Follow_Up_Date__c
            FROM Call_Log__c
            WHERE Id = :callLog.Id
        ];
        existingLead = [SELECT Next_Follow_Up_Date__c FROM Lead__c WHERE Id = :existingLead.Id];

        Integer phoneCount = [
            SELECT Count()
            FROM Phone_Number__c
            WHERE Name = '1111111111'
            AND Candidate__c = :existingLead.Candidate__c
        ];
    }

    @IsTest
    static void testTagOrCreateLead_NewLead() {
        Call_Log__c callLog = new Call_Log__c(
            Phone_Number__c = '9999999999',
            Feedback__c = 'Fresh call',
            Untracked__c = true
        );
        insert callLog;

        Id leadRecTypeId = getLeadRecordTypeId();
        String courseValue = getCourseValueForRecordType(leadRecTypeId);

        TagLeadController.tagOrCreateLead(
            callLog.Id,
            null,
            'New Lead',
            courseValue,
            'newlead@test.com',
            '9999999999',
            true,
            'L1',
            'L2',
            'New feedback',
            '2026-02-16T15:00',
            leadRecTypeId
        );

        Lead__c newLead = [
            SELECT Id, Name, Course__c, Candidate__c, Next_Follow_Up_Date__c, Disable_Round_Robin__c
            FROM Lead__c
            WHERE Name = 'New Lead'
            LIMIT 1
        ];
        Lead standardLead = [SELECT Id FROM Lead WHERE Id = :newLead.Candidate__c LIMIT 1];

        callLog = [
            SELECT Lead__c, Feedback__c, Untracked__c, Next_Follow_Up_Date__c
            FROM Call_Log__c
            WHERE Id = :callLog.Id
        ];
    }

    @IsTest
    static void testMarkPhoneNumberAsSpam() {
        Call_Log__c callLog = [
            SELECT Id
            FROM Call_Log__c
            WHERE Phone_Number__c = '1111111111'
            LIMIT 1
        ];

        Test.startTest();
        TagLeadController.markPhoneNumberStatus(callLog.Id, true, false);
        Test.stopTest();

        Phone_Number__c phoneRecord = [
            SELECT Id, Phone__c, Is_Spam__c, Is_DND__c
            FROM Phone_Number__c
            WHERE Phone__c = '1111111111'
            LIMIT 1
        ];
    }

    @IsTest
    static void testMarkPhoneNumberAsDnd() {
        Call_Log__c callLog = new Call_Log__c(
            Phone_Number__c = '8888888888',
            Feedback__c = 'DND call',
            Untracked__c = true
        );
        insert callLog;

        Test.startTest();
        TagLeadController.markPhoneNumberStatus(callLog.Id, false, true);
        Test.stopTest();

        Phone_Number__c phoneRecord = [
            SELECT Id, Phone__c, Is_Spam__c, Is_DND__c
            FROM Phone_Number__c
            WHERE Phone__c = '8888888888'
            LIMIT 1
        ];
    }

    private static Id getLeadRecordTypeId() {
        Schema.DescribeSObjectResult dsr = Lead__c.SObjectType.getDescribe();
        for (Schema.RecordTypeInfo rti : dsr.getRecordTypeInfos()) {
            if (rti.isAvailable() && !rti.isMaster() && rti.isDefaultRecordTypeMapping()) {
                return rti.getRecordTypeId();
            }
        }
        for (Schema.RecordTypeInfo rti : dsr.getRecordTypeInfos()) {
            if (rti.isAvailable() && !rti.isMaster()) {
                return rti.getRecordTypeId();
            }
        }
        return null;
    }

    private static String getCourseValueForRecordType(Id recordTypeId) {
        if (recordTypeId == null) {
            return null;
        }
        return 'CPA';
    }
}