force-app/main/default/objects/Call_Log__c/Call_Log__c.object-meta.xml
<CustomObject>
    <label>Call Log</label>
    <nameField>
        <displayFormat>Call Log - {0000}</displayFormat>
        <label>Call Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Log__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Call Logs</relationshipLabel>
    <relationshipName>Call_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Log__c/fields/Created_At__c.field-meta.xml
<CustomField>
    <fullName>Created_At__c</fullName>
    <label>Created At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Call_Log__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Call Logs</relationshipLabel>
    <relationshipName>Call_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Log__c/fields/Next_Follow_Up_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Follow_Up_Date__c</fullName>
    <label>Next Follow Up Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Call_Log__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <label>Phone Number (Customer)</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Call_Log__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>M_Stages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>incoming</fullName>
            </value>
            <value>
                <fullName>outgoing</fullName>
            </value>
            <value>
                <fullName>missed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Log__c/fields/Untracked__c.field-meta.xml
<CustomField>
    <fullName>Untracked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Untracked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Email__c/Email__c.object-meta.xml
<CustomObject>
    <label>Email</label>
    <nameField>
        <displayFormat>Email - {0000}</displayFormat>
        <label>Email Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Email__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Emails</relationshipLabel>
    <relationshipName>Emails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Email__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Emails</relationshipLabel>
    <relationshipName>Emails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Candidate_ID__c.field-meta.xml
<CustomField>
    <fullName>Candidate_ID__c</fullName>
    <label>Candidate ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Course</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Is_Merged__c.field-meta.xml
<CustomField>
    <fullName>Is_Merged__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Merged</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phone Number</label>
    <referenceTo>Phone_Number__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Source_Bucket__c.field-meta.xml
<CustomField>
    <fullName>Source_Bucket__c</fullName>
    <formula>IF(
    ISPICKVAL( Coming_From__c, &quot;Facebook&quot;) ||
    ISPICKVAL(Coming_From__c, &quot;Advertisement&quot;) ||
    ISPICKVAL(Coming_From__c, &quot;website-contact_us&quot;) ||
    ISPICKVAL(Coming_From__c, &quot;Google Ads&quot;),
    &quot;Bucket 1&quot;,

IF(
    ISPICKVAL(Coming_From__c, &quot;Website&quot;) ||
    ISPICKVAL(Coming_From__c, &quot;Landing Page&quot;),
    &quot;Bucket 2&quot;,

IF(
    ISPICKVAL(Coming_From__c, &quot;Referral&quot;) ||
    ISPICKVAL(Coming_From__c, &quot;Partner&quot;),
    &quot;Bucket 3&quot;,

&quot;Bucket 4&quot;
)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Source Bucket</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Course</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Is_DND__c.field-meta.xml
<CustomField>
    <fullName>Is_DND__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is DND</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Is_Merged__c.field-meta.xml
<CustomField>
    <fullName>Is_Merged__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Merged</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Is_ReEnquiry__c.field-meta.xml
<CustomField>
    <fullName>Is_ReEnquiry__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is ReEnquiry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Is_Spam__c.field-meta.xml
<CustomField>
    <fullName>Is_Spam__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Spam</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Next_Follow_Up_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Follow_Up_Date__c</fullName>
    <label>Next Follow Up Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Primary_tag__c.field-meta.xml
<CustomField>
    <fullName>Primary_tag__c</fullName>
    <label>Primary tag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Primary_tag</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Source_Bucket__c.field-meta.xml
<CustomField>
    <fullName>Source_Bucket__c</fullName>
    <label>Source Bucket</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Bucket</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>M_Stages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Phone_Number__c/Phone_Number__c.object-meta.xml
<CustomObject>
    <label>Phone Number</label>
    <nameField>
        <displayFormat>Phone - {0000}</displayFormat>
        <label>Phone Number Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Phone Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Phone_Number__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Phone Numbers</relationshipLabel>
    <relationshipName>Phone_Numbers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Phone_Number__c/fields/Is_DND__c.field-meta.xml
<CustomField>
    <fullName>Is_DND__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is DND</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Phone_Number__c/fields/Is_Spam__c.field-meta.xml
<CustomField>
    <fullName>Is_Spam__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Spam</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Phone_Number__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Phone Numbers</relationshipLabel>
    <relationshipName>Phone_Numbers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Source_Bucket__c/Source_Bucket__c.object-meta.xml
<CustomObject>
    <label>Source Bucket</label>
    <nameField>
        <label>Source Bucket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Source Buckets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Source_Bucket__c/fields/source__c.field-meta.xml
<CustomField>
    <fullName>source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>City</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Bucket.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bucket 1</fullName>
    </customValue>
    <customValue>
        <fullName>Bucket 2</fullName>
    </customValue>
    <customValue>
        <fullName>Bucket 3</fullName>
    </customValue>
    <customValue>
        <fullName>Bucket 4</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
    </customValue>
    <masterLabel>Bucket</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/City.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Ahmedabad</fullName>
    </customValue>
    <customValue>
        <fullName>Bangalore</fullName>
    </customValue>
    <customValue>
        <fullName>Chennai</fullName>
    </customValue>
    <customValue>
        <fullName>Delhi</fullName>
    </customValue>
    <customValue>
        <fullName>Dubai</fullName>
    </customValue>
    <customValue>
        <fullName>Ernakulam</fullName>
    </customValue>
    <customValue>
        <fullName>Hyderabad</fullName>
    </customValue>
    <customValue>
        <fullName>Kolkata</fullName>
    </customValue>
    <customValue>
        <fullName>Mumbai</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Pune</fullName>
    </customValue>
    <masterLabel>City</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Course.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CMA</fullName>
    </customValue>
    <customValue>
        <fullName>CPA</fullName>
    </customValue>
    <customValue>
        <fullName>CAIRA</fullName>
    </customValue>
    <customValue>
        <fullName>MCOM</fullName>
    </customValue>
    <customValue>
        <fullName>US Pathway</fullName>
    </customValue>
    <masterLabel>Course</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/M_Stages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>M1</fullName>
    </customValue>
    <customValue>
        <fullName>M2</fullName>
    </customValue>
    <customValue>
        <fullName>M3</fullName>
    </customValue>
    <customValue>
        <fullName>M3+</fullName>
    </customValue>
    <customValue>
        <fullName>M3++</fullName>
    </customValue>
    <customValue>
        <fullName>M4-</fullName>
    </customValue>
    <customValue>
        <fullName>M4</fullName>
    </customValue>
    <customValue>
        <fullName>M5</fullName>
    </customValue>
    <customValue>
        <fullName>M6</fullName>
    </customValue>
    <customValue>
        <fullName>M7</fullName>
    </customValue>
    <customValue>
        <fullName>M7+</fullName>
    </customValue>
    <customValue>
        <fullName>B1</fullName>
    </customValue>
    <customValue>
        <fullName>B2</fullName>
    </customValue>
    <customValue>
        <fullName>B3</fullName>
    </customValue>
    <customValue>
        <fullName>B3+</fullName>
    </customValue>
    <customValue>
        <fullName>B3++</fullName>
    </customValue>
    <customValue>
        <fullName>B4-</fullName>
    </customValue>
    <customValue>
        <fullName>B4</fullName>
    </customValue>
    <customValue>
        <fullName>B5</fullName>
    </customValue>
    <customValue>
        <fullName>B6</fullName>
    </customValue>
    <customValue>
        <fullName>B7</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
    </customValue>
    <customValue>
        <fullName>M7#</fullName>
    </customValue>
    <customValue>
        <fullName>U1</fullName>
    </customValue>
    <customValue>
        <fullName>U2</fullName>
    </customValue>
    <customValue>
        <fullName>U3</fullName>
    </customValue>
    <customValue>
        <fullName>U3+</fullName>
    </customValue>
    <customValue>
        <fullName>U3++</fullName>
    </customValue>
    <customValue>
        <fullName>U4-</fullName>
    </customValue>
    <customValue>
        <fullName>U4</fullName>
    </customValue>
    <masterLabel>M Stages</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Primary_tag.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Todays</fullName>
    </customValue>
    <customValue>
        <fullName>Delays</fullName>
    </customValue>
    <customValue>
        <fullName>Missed calls</fullName>
    </customValue>
    <customValue>
        <fullName>Untracked calls</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <customValue>
        <fullName>MHP</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>Primary tag</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Facebook</fullName>
    </customValue>
    <customValue>
        <fullName>Advertisement</fullName>
    </customValue>
    <customValue>
        <fullName>website-contact_us</fullName>
    </customValue>
    <customValue>
        <fullName>Website</fullName>
    </customValue>
    <customValue>
        <fullName>Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Google Ads</fullName>
    </customValue>
    <customValue>
        <fullName>IVR</fullName>
    </customValue>
    <customValue>
        <fullName>Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Whatsapp Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>WhatsApp BOT on Website</fullName>
    </customValue>
    <customValue>
        <fullName>Live Chat on Website</fullName>
    </customValue>
    <customValue>
        <fullName>SuperBot</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook Ads</fullName>
    </customValue>
    <customValue>
        <fullName>Email Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Miles One App</fullName>
    </customValue>
    <customValue>
        <fullName>Referral - Manual</fullName>
    </customValue>
    <customValue>
        <fullName>Zoom Webinar</fullName>
    </customValue>
    <customValue>
        <fullName>Social</fullName>
    </customValue>
    <customValue>
        <fullName>TimesInternet</fullName>
    </customValue>
    <customValue>
        <fullName>SMS Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Newsletter Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Youtube</fullName>
    </customValue>
    <customValue>
        <fullName>Live Chat</fullName>
    </customValue>
    <customValue>
        <fullName>Incoming Call</fullName>
    </customValue>
    <customValue>
        <fullName>Instagram</fullName>
    </customValue>
    <customValue>
        <fullName>CA-DB</fullName>
    </customValue>
    <customValue>
        <fullName>Blog Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Times Jobs</fullName>
    </customValue>
    <customValue>
        <fullName>Placement Drive</fullName>
    </customValue>
    <customValue>
        <fullName>Naukri</fullName>
    </customValue>
    <masterLabel>Source</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LeadQueueManagementController.cls
/*
    Author       : ROHIT SINGH BISHT
    Description  : 
*/
public class LeadQueueManagementController {

    @AuraEnabled(cacheable=true)
    public static List<LeadQueueItemDTO> getUserLeads() {
        List<Lead__c> leads = [SELECT Id, Name, Phone__c, Email__c, Course__c, City__c, Stage__c, Source__c, CreatedDate, Primary_tag__c, Source_Bucket__c, Next_Follow_Up_Date__c, Candidate__c, Candidate__r.Candidate_ID__c, Is_ReEnquiry__c FROM Lead__c WHERE OwnerId = :UserInfo.getUserId() AND Is_DND__c = FALSE AND Is_Spam__c = FALSE AND Is_Merged__c = FALSE AND (Next_Follow_Up_Date__c = NULL OR Next_Follow_Up_Date__c <= :Datetime.now()) ORDER BY CreatedDate DESC LIMIT 200];

        System.debug('LeadQueueManagementController.getUserLeads: fetched leads count = ' + leads);
        List<Call_Log__c> callLogs = [SELECT Id, Customer_Name__c, Phone_Number__c, CreatedDate, Type__c, Candidate__c, Candidate__r.Candidate_ID__c FROM Call_Log__c WHERE OwnerId = :UserInfo.getUserId() AND Lead__c = null AND Next_Follow_Up_Date__c = null AND (Untracked__c = TRUE OR (Type__c = 'missed' AND Candidate__c != null)) ORDER BY CreatedDate DESC LIMIT 200];

        User currentUser = [SELECT Id, UserRole.Name FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1 ];

        Map<Id, String> latestCallStatusByLeadId = new Map<Id, String>();

        if (!leads.isEmpty()) {
            Set<Id> leadIds = new Set<Id>();
            for (Lead__c l : leads) {
                leadIds.add(l.Id);
            }

            List<Call_Log__c> leadCallLogs = [ SELECT Id, Lead__c, Type__c, Created_At__c FROM Call_Log__c WHERE Lead__c IN :leadIds ORDER BY Lead__c, Created_At__c DESC ];

            for (Call_Log__c log : leadCallLogs) {
                if (!latestCallStatusByLeadId.containsKey(log.Lead__c)) {
                    latestCallStatusByLeadId.put(log.Lead__c, log.Type__c);
                }
            }
        }

        List<LeadQueueItemDTO> allItems = new List<LeadQueueItemDTO>();

        for (Lead__c l : leads) {
            LeadQueueItemDTO dto = new LeadQueueItemDTO();
            dto.id          = l.Id;
            dto.name        = l.Name;
            dto.phone       = l.Phone__c;
            dto.course      = l.Course__c;
            dto.city        = l.City__c;
            dto.stage       = l.Stage__c;
            dto.source      = l.Source_Bucket__c;
            dto.createdDate = l.CreatedDate;
            dto.iscallLog   = false;

            String lastCallStatus = latestCallStatusByLeadId.get(l.Id);

            dto.primaryTag = derivePrimaryTag(l.Next_Follow_Up_Date__c, lastCallStatus, l.Candidate__c, l.Is_ReEnquiry__c);

            dto.roleTag   = currentUser.UserRole != null ? currentUser.UserRole.Name : null;
            dto.bucketTag = l.Source_Bucket__c;
            dto.nextFollowUpDate = l.Next_Follow_Up_Date__c;
            dto.candidateId = l.Candidate__c;
            dto.candidateCode = l.Candidate__r != null ? l.Candidate__r.Candidate_ID__c : null;
            allItems.add(dto);
        }

        for (Call_Log__c e : callLogs) {
            LeadQueueItemDTO dto = new LeadQueueItemDTO();
            dto.id          = e.Id;
            dto.name        = e.Customer_Name__c;
            dto.phone       = e.Phone_Number__c;
            dto.course      = 'NA';
            dto.city        = 'NA';
            dto.stage       = 'NA';
            dto.source      = 'NA';
            dto.createdDate = e.CreatedDate;
            dto.iscallLog   = true;
            dto.primaryTag  = (!String.isBlank(e.Type__c) && e.Type__c.equalsIgnoreCase('missed'))
                ? 'Missed calls'
                : 'Untracked calls';
            // dto.primaryTag  = 'Unknown';
            dto.roleTag     = currentUser.UserRole != null ? currentUser.UserRole.Name : null;
            dto.bucketTag   = 'ALL';
            dto.candidateId = e.Candidate__c;
            dto.candidateCode = e.Candidate__r != null ? e.Candidate__r.Candidate_ID__c : null;
            allItems.add(dto);
        }

        List<LeadQueueItemDTO> prioritizedItems = QueuePriorityService.assignPriorities(allItems);
        System.debug('LeadQueueManagementController.getUserLeads: prioritizedItems = ' + prioritizedItems);
        return prioritizedItems;
    }

    public static String derivePrimaryTag(Datetime nextFollowupDate, String callStatus, Id canId, Boolean isReEnquiry) {
        Datetime nowDt = Datetime.now();
        Date todayDate = nowDt.date();
        Datetime startOfToday = Datetime.newInstance(todayDate, Time.newInstance(0, 0, 0, 0));
        Datetime startOfTomorrow = startOfToday.addDays(1);

        if (!String.isBlank(callStatus) && callStatus.equalsIgnoreCase('missed')) {
            return 'Missed calls';
        }
                
        if (nextFollowupDate != null) {
            if (nextFollowupDate >= startOfToday && nextFollowupDate < startOfTomorrow) {
                return 'Todays';
            }
            if (nextFollowupDate < startOfToday) {
                return 'Delays';
            }
        }

        if (isReEnquiry == true) {
            return 'MHP';
        }

        return 'NE';
    }
}