force-app/main/default/objects/Email__c/Email__c.object-meta.xml
<CustomObject>
    <label>Email</label>
    <nameField>
        <displayFormat>Email - {0000}</displayFormat>
        <label>Email Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Email__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Emails</relationshipLabel>
    <relationshipName>Emails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Email__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Emails</relationshipLabel>
    <relationshipName>Emails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Candidate_ID__c.field-meta.xml
<CustomField>
    <fullName>Candidate_ID__c</fullName>
    <label>Candidate ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Course</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Is_Merged__c.field-meta.xml
<CustomField>
    <fullName>Is_Merged__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Merged</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Source_Bucket__c.field-meta.xml
<CustomField>
    <fullName>Source_Bucket__c</fullName>
    <formula>IF(
    ISPICKVAL( Coming_From__c, &quot;Facebook&quot;) ||
    ISPICKVAL(Coming_From__c, &quot;Advertisement&quot;) ||
    ISPICKVAL(Coming_From__c, &quot;website-contact_us&quot;) ||
    ISPICKVAL(Coming_From__c, &quot;Google Ads&quot;),
    &quot;Bucket 1&quot;,

IF(
    ISPICKVAL(Coming_From__c, &quot;Website&quot;) ||
    ISPICKVAL(Coming_From__c, &quot;Landing Page&quot;),
    &quot;Bucket 2&quot;,

IF(
    ISPICKVAL(Coming_From__c, &quot;Referral&quot;) ||
    ISPICKVAL(Coming_From__c, &quot;Partner&quot;),
    &quot;Bucket 3&quot;,

&quot;Bucket 4&quot;
)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Source Bucket</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Course</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/GP_User__c.field-meta.xml
<CustomField>
    <fullName>GP_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GP User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Is_DND__c.field-meta.xml
<CustomField>
    <fullName>Is_DND__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is DND</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Is_Merged__c.field-meta.xml
<CustomField>
    <fullName>Is_Merged__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Merged</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Is_ReEnquiry__c.field-meta.xml
<CustomField>
    <fullName>Is_ReEnquiry__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is ReEnquiry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Is_Spam__c.field-meta.xml
<CustomField>
    <fullName>Is_Spam__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Spam</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Next_Follow_Up_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Follow_Up_Date__c</fullName>
    <label>Next Follow Up Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Primary_tag__c.field-meta.xml
<CustomField>
    <fullName>Primary_tag__c</fullName>
    <label>Primary tag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Primary_tag</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Queue_Stage__c.field-meta.xml
<CustomField>
    <fullName>Queue_Stage__c</fullName>
    <label>Queue Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Q1</fullName>
            </value>
            <value>
                <fullName>Q2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Source_Bucket__c.field-meta.xml
<CustomField>
    <fullName>Source_Bucket__c</fullName>
    <label>Source Bucket</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Bucket</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>M_Stages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Queue_Lead_Status__e/Queue_Lead_Status__e.object-meta.xml
<CustomObject>
    <label>Queue Lead Status</label>
    <pluralLabel>Queue Lead Status</pluralLabel>
</CustomObject>

force-app/main/default/objects/Source_Bucket__c/Source_Bucket__c.object-meta.xml
<CustomObject>
    <label>Source Bucket</label>
    <nameField>
        <label>Source Bucket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Source Buckets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>City</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Bucket.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bucket 1</fullName>
    </customValue>
    <customValue>
        <fullName>Bucket 2</fullName>
    </customValue>
    <customValue>
        <fullName>Bucket 3</fullName>
    </customValue>
    <customValue>
        <fullName>Bucket 4</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
    </customValue>
    <masterLabel>Bucket</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/City.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Ahmedabad</fullName>
    </customValue>
    <customValue>
        <fullName>Bangalore</fullName>
    </customValue>
    <customValue>
        <fullName>Chennai</fullName>
    </customValue>
    <customValue>
        <fullName>Delhi</fullName>
    </customValue>
    <customValue>
        <fullName>Dubai</fullName>
    </customValue>
    <customValue>
        <fullName>Ernakulam</fullName>
    </customValue>
    <customValue>
        <fullName>Hyderabad</fullName>
    </customValue>
    <customValue>
        <fullName>Kolkata</fullName>
    </customValue>
    <customValue>
        <fullName>Mumbai</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Pune</fullName>
    </customValue>
    <masterLabel>City</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Course.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CMA</fullName>
    </customValue>
    <customValue>
        <fullName>CPA</fullName>
    </customValue>
    <customValue>
        <fullName>CAIRA</fullName>
    </customValue>
    <customValue>
        <fullName>MCOM</fullName>
    </customValue>
    <customValue>
        <fullName>US Pathway</fullName>
    </customValue>
    <masterLabel>Course</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/M_Stages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>M1</fullName>
    </customValue>
    <customValue>
        <fullName>M2</fullName>
    </customValue>
    <customValue>
        <fullName>M3</fullName>
    </customValue>
    <customValue>
        <fullName>M3+</fullName>
    </customValue>
    <customValue>
        <fullName>M3++</fullName>
    </customValue>
    <customValue>
        <fullName>M4-</fullName>
    </customValue>
    <customValue>
        <fullName>M4</fullName>
    </customValue>
    <customValue>
        <fullName>M5</fullName>
    </customValue>
    <customValue>
        <fullName>M6</fullName>
    </customValue>
    <customValue>
        <fullName>M7</fullName>
    </customValue>
    <customValue>
        <fullName>M7+</fullName>
    </customValue>
    <customValue>
        <fullName>B1</fullName>
    </customValue>
    <customValue>
        <fullName>B2</fullName>
    </customValue>
    <customValue>
        <fullName>B3</fullName>
    </customValue>
    <customValue>
        <fullName>B3+</fullName>
    </customValue>
    <customValue>
        <fullName>B3++</fullName>
    </customValue>
    <customValue>
        <fullName>B4-</fullName>
    </customValue>
    <customValue>
        <fullName>B4</fullName>
    </customValue>
    <customValue>
        <fullName>B5</fullName>
    </customValue>
    <customValue>
        <fullName>B6</fullName>
    </customValue>
    <customValue>
        <fullName>B7</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
    </customValue>
    <customValue>
        <fullName>M7#</fullName>
    </customValue>
    <customValue>
        <fullName>U1</fullName>
    </customValue>
    <customValue>
        <fullName>U2</fullName>
    </customValue>
    <customValue>
        <fullName>U3</fullName>
    </customValue>
    <customValue>
        <fullName>U3+</fullName>
    </customValue>
    <customValue>
        <fullName>U3++</fullName>
    </customValue>
    <customValue>
        <fullName>U4-</fullName>
    </customValue>
    <customValue>
        <fullName>U4</fullName>
    </customValue>
    <masterLabel>M Stages</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Primary_tag.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Todays</fullName>
    </customValue>
    <customValue>
        <fullName>Delays</fullName>
    </customValue>
    <customValue>
        <fullName>Missed calls</fullName>
    </customValue>
    <customValue>
        <fullName>Untracked calls</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <customValue>
        <fullName>MHP</fullName>
    </customValue>
    <customValue>
        <fullName>All</fullName>
    </customValue>
    <masterLabel>Primary tag</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LeadQ2QueueController.cls
public without sharing class LeadQ2QueueController {

    @AuraEnabled(cacheable=true)
    public static List<LeadQueueItemDTO> getQ2Leads() {
        User currentUser = [SELECT Id, City__c, UserRole.Name FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];
        String userCity = currentUser.City__c;
        String queueSearchName = userCity + ' Public Queue';
        List<Lead> candidates = [SELECT Id, Name, Candidate_ID__c, Next_Follow_Up_Date__c, (SELECT Id, Name, Phone__c, Email__c, Course__c, City__c, Stage__c, Source_Bucket__c, CreatedDate, Primary_tag__c, Candidate__c, Is_ReEnquiry__c, Queue_Stage__c FROM Leads__r WHERE Owner.Type = 'Queue' AND Owner.Name = :queueSearchName AND Queue_Stage__c = 'Q2' AND Is_DND__c = FALSE AND Is_Spam__c = FALSE AND Is_Merged__c = FALSE ORDER BY CreatedDate DESC) FROM Lead WHERE Id IN (SELECT Candidate__c FROM Lead__c WHERE Candidate__c != null AND Owner.Type = 'Queue' AND Owner.Name = :queueSearchName AND Queue_Stage__c = 'Q2' AND Is_DND__c = FALSE AND Is_Spam__c = FALSE AND Is_Merged__c = FALSE) LIMIT 200];
        return QueuePriorityService.assignPriorities(buildQueueItems(candidates, currentUser));
    }

    private static List<LeadQueueItemDTO> buildQueueItems(List<Lead> candidates, User currentUser) {
        List<LeadQueueItemDTO> items = new List<LeadQueueItemDTO>();
        for (Lead candidate : candidates) {
            List<SObject> relatedLeadRecords = candidate.getSObjects('Leads__r');
            if (relatedLeadRecords == null || relatedLeadRecords.isEmpty()) {
                continue;
            }

            for (SObject relatedLeadRecord : relatedLeadRecords) {
                Lead__c relatedLead = (Lead__c) relatedLeadRecord;
                LeadQueueItemDTO dto = new LeadQueueItemDTO();
                dto.id = relatedLead.Id;
                dto.name = relatedLead.Name;
                dto.phone = relatedLead.Phone__c;
                dto.course = relatedLead.Course__c;
                dto.city = relatedLead.City__c;
                dto.stage = relatedLead.Stage__c;
                dto.source = relatedLead.Source_Bucket__c;
                dto.createdDate = relatedLead.CreatedDate;
                dto.iscallLog = false;
                dto.primaryTag = derivePrimaryTag(candidate.Next_Follow_Up_Date__c, null, candidate.Id, relatedLead.Is_ReEnquiry__c);
                dto.roleTag = currentUser.UserRole != null ? currentUser.UserRole.Name : null;
                dto.bucketTag = relatedLead.Source_Bucket__c;
                dto.nextFollowUpDate = candidate.Next_Follow_Up_Date__c;
                dto.candidateId = candidate.Id;
                dto.candidateCode = candidate.Candidate_ID__c;
                dto.candidateName = candidate.Name;
                items.add(dto);
            }
        }
        return items;
    }

    @AuraEnabled
    public static void startProcessingLead(Id leadId, String status) {
        if (leadId == null) return;
        Queue_Lead_Status__e evt = new Queue_Lead_Status__e();
        evt.Lead_Id__c = leadId;
        evt.Status__c = String.isBlank(status) ? 'Processing' : status;
        EventBus.publish(evt);
    }

    @AuraEnabled
    public static void updateLeadOwner(Id leadId, Id candidateId) {
        if (leadId == null && candidateId == null) return;

        List<SObject> recordsToUpdate = new List<SObject>();

        if (leadId != null) {
            recordsToUpdate.add(new Lead__c(
                Id = leadId,
                OwnerId = UserInfo.getUserId()
            ));
        }

        if (candidateId != null) {
            recordsToUpdate.add(new Lead(
                Id = candidateId,
                OwnerId = UserInfo.getUserId()
            ));
        }

        if (!recordsToUpdate.isEmpty()) {
            update recordsToUpdate;
        }
    }

    public static String derivePrimaryTag(Datetime nextFollowupDate, String callStatus, Id canId, Boolean isReEnquiry) {
        Datetime nowDt = Datetime.now();
        Date todayDate = nowDt.date();
        Datetime startOfToday = Datetime.newInstance(todayDate, Time.newInstance(0, 0, 0, 0));
        Datetime startOfTomorrow = startOfToday.addDays(1);

        if (!String.isBlank(callStatus) && callStatus.equalsIgnoreCase('missed')) {
            return 'Missed calls';
        }
                
        if (nextFollowupDate != null) {
            if (nextFollowupDate >= startOfToday && nextFollowupDate < startOfTomorrow) {
                return 'Todays';
            }
            if (nextFollowupDate < startOfToday) {
                return 'Delays';
            }
        }

        if (isReEnquiry == true) {
            return 'MHP';
        }

        return 'NE';
    }
}