force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RoundRobinConfigProviderTest.cls
@IsTest(seeAllData=true)
public class RoundRobinConfigProviderTest {

    @IsTest
    static void testConfigFound() {

        RoundRobinConfigProvider.Config cfg =
            RoundRobinConfigProvider.getConfig('Lead__c', 'CC - Pre Enrollment');

        System.assertNotEquals(null, cfg);
        System.assertEquals('Lead__c', cfg.objectApiName);
        System.assertEquals('CC - Pre Enrollment', cfg.typeValue);
    }

    @IsTest
    static void testConfigMissing() {

        RoundRobinConfigProvider.Config cfg =
            RoundRobinConfigProvider.getConfig('Invalid__c', 'X');

        System.assertEquals(null, cfg);
    }

    @IsTest
    static void testDefaultTypeHandling() {

        RoundRobinConfigProvider.Config cfg =
            RoundRobinConfigProvider.getConfig('Lead__c', null);

        System.assertNotEquals(null, cfg);
    }
}