force-app/main/default/objects/Eligibility_File__c/Eligibility_File__c.object-meta.xml
<CustomObject>
    <label>Eligibility File</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eligibility File</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Eligibility_File__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Lead</relationshipLabel>
    <relationshipName>Lead</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eligibility_File__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Reupload_Required</fullName>
            </value>
            <value>
                <fullName>Recheck</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Re-uploaded</fullName>
            </value>
            <value>
                <fullName>Superseded</fullName>
                <isActive>false</isActive>
                <label>Superseded</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Course</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Payment_Received__c.field-meta.xml
<CustomField>
    <fullName>Payment_Received__c</fullName>
    <label>Payment Received</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fully Received</fullName>
            </value>
            <value>
                <fullName>Partially Received</fullName>
            </value>
            <value>
                <fullName>Not Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>M_Stages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/recordTypes/CAIRA.recordType-meta.xml
<RecordType>
    <fullName>CAIRA</fullName>
    <active>true</active>
    <label>CAIRA</label>
</RecordType>

force-app/main/default/objects/Lead__c/recordTypes/CMA.recordType-meta.xml
<RecordType>
    <fullName>CMA</fullName>
    <active>true</active>
    <label>CMA</label>
</RecordType>

force-app/main/default/objects/Lead__c/recordTypes/CPA.recordType-meta.xml
<RecordType>
    <fullName>CPA</fullName>
    <active>true</active>
    <label>CPA</label>
</RecordType>

force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>LOAN - {0000}</displayFormat>
        <label>Loan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Loan_Id__c.field-meta.xml
<CustomField>
    <fullName>Loan_Id__c</fullName>
    <label>Loan Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO -{0000}</displayFormat>
        <label>Purchase Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Net_Payable_Amount__c.field-meta.xml
<CustomField>
    <fullName>Net_Payable_Amount__c</fullName>
    <formula>Total_Amount__c - Discount_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Payable Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Purchase_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order_Id__c</fullName>
    <label>Purchase Order Id</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Confirmed,</fullName>
            </value>
            <value>
                <fullName>Paid,</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Total_Payment_Received__c.field-meta.xml
<CustomField>
    <fullName>Total_Payment_Received__c</fullName>
    <label>Total Payment Received</label>
    <summarizedField>Transcation__c.Payment__c</summarizedField>
    <summaryFilterItems>
        <field>Transcation__c.Status__c</field>
        <operation>equals</operation>
        <value>Received</value>
    </summaryFilterItems>
    <summaryForeignKey>Transcation__c.Purchase_Orders__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Transcation__c/Transcation__c.object-meta.xml
<CustomObject>
    <label>Transcation</label>
    <nameField>
        <displayFormat>Transcation-{0000}</displayFormat>
        <label>Transcation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transcations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transcation__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Transcations</relationshipLabel>
    <relationshipName>Transcations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transcation__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <label>Payment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transcation__c/fields/Purchase_Orders__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Orders__c</fullName>
    <label>Purchase Orders</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Transcations (Purchase Orders)</relationshipLabel>
    <relationshipName>Transcations1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transcation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Initiated</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transcation__c/fields/Transcation_Id__c.field-meta.xml
<CustomField>
    <fullName>Transcation_Id__c</fullName>
    <label>Transcation Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Course.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CMA</fullName>
    </customValue>
    <customValue>
        <fullName>CPA</fullName>
    </customValue>
    <customValue>
        <fullName>CAIRA</fullName>
    </customValue>
    <customValue>
        <fullName>MCOM</fullName>
    </customValue>
    <customValue>
        <fullName>US Pathway</fullName>
    </customValue>
    <masterLabel>Course</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/M_Stages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>M1</fullName>
    </customValue>
    <customValue>
        <fullName>M2</fullName>
    </customValue>
    <customValue>
        <fullName>M3</fullName>
    </customValue>
    <customValue>
        <fullName>M3+</fullName>
    </customValue>
    <customValue>
        <fullName>M3++</fullName>
    </customValue>
    <customValue>
        <fullName>M4-</fullName>
    </customValue>
    <customValue>
        <fullName>M4</fullName>
    </customValue>
    <customValue>
        <fullName>M5</fullName>
    </customValue>
    <customValue>
        <fullName>M6</fullName>
    </customValue>
    <customValue>
        <fullName>M7</fullName>
    </customValue>
    <customValue>
        <fullName>M7+</fullName>
    </customValue>
    <customValue>
        <fullName>B1</fullName>
    </customValue>
    <customValue>
        <fullName>B2</fullName>
    </customValue>
    <customValue>
        <fullName>B3</fullName>
    </customValue>
    <customValue>
        <fullName>B3+</fullName>
    </customValue>
    <customValue>
        <fullName>B3++</fullName>
    </customValue>
    <customValue>
        <fullName>B4-</fullName>
    </customValue>
    <customValue>
        <fullName>B4</fullName>
    </customValue>
    <customValue>
        <fullName>B5</fullName>
    </customValue>
    <customValue>
        <fullName>B6</fullName>
    </customValue>
    <customValue>
        <fullName>B7</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
    </customValue>
    <customValue>
        <fullName>M7#</fullName>
    </customValue>
    <customValue>
        <fullName>U1</fullName>
    </customValue>
    <customValue>
        <fullName>U2</fullName>
    </customValue>
    <customValue>
        <fullName>U3</fullName>
    </customValue>
    <customValue>
        <fullName>U3+</fullName>
    </customValue>
    <customValue>
        <fullName>U3++</fullName>
    </customValue>
    <customValue>
        <fullName>U4-</fullName>
    </customValue>
    <customValue>
        <fullName>U4</fullName>
    </customValue>
    <customValue>
        <fullName>U7</fullName>
    </customValue>
    <masterLabel>M Stages</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Webhook_PaymentUpdateApi.cls
/**
 * Author: Rohit Singh Bisht
 * Created: 2026-02-10
 */
@RestResource(urlMapping='/payment/update')
global without sharing class Webhook_PaymentUpdateApi {

    @HttpPost
    global static ApiResponse updatePayment() {
        ApiResponse response = new ApiResponse();

        RestRequest req = RestContext.request;
        String serviceName = 'Webhook Payment Update';
        String requestPayload = truncate(req != null && req.requestBody != null ? req.requestBody.toString() : null);

        if (req == null || req.requestBody == null || String.isBlank(req.requestBody.toString())) {
            response.success = false;
            response.message = 'Empty request body';

            IntegrationLogUtil.insertLog(serviceName, requestPayload, null, response.message, 'Failed', 400);
            return response;
        }

        PaymentRequest paymentReq;
        try {
            paymentReq = (PaymentRequest) JSON.deserialize(req.requestBody.toString(), PaymentRequest.class);
        } catch (Exception e) {
            response.success = false;
            response.message = 'Invalid JSON: ' + e.getMessage();

            IntegrationLogUtil.insertLog(serviceName, requestPayload, null, response.message, 'Failed', 400);
            return response;
        }

        String purchaseKey = !String.isBlank(paymentReq.purchaseId)
            ? paymentReq.purchaseId
            : paymentReq.purchase_id;
        String loanKey = !String.isBlank(paymentReq.loanId)
            ? paymentReq.loanId
            : paymentReq.loan_id;
        String transactionType = !String.isBlank(paymentReq.transactionType)
            ? paymentReq.transactionType
            : paymentReq.transaction_type;

        if (String.isBlank(purchaseKey)) {
            response.success = false;
            response.message = 'Purchase Order Id is required';

            IntegrationLogUtil.insertLog(serviceName, requestPayload, null, response.message, 'Failed', 400);
            return response;
        }

        if (String.isBlank(paymentReq.transactionId)) {
            response.success = false;
            response.message = 'Transaction Id is required';

            IntegrationLogUtil.insertLog(serviceName, requestPayload, null, response.message, 'Failed', 400);
            return response;
        }

        try {
            Purchase_Order__c po = [
                SELECT Id, Net_Payable_Amount__c, Lead__c, Lead__r.Payment_Received__c, Lead__r.Stage__c, Lead__r.Course__c
                FROM Purchase_Order__c
                WHERE Purchase_Order_Id__c = :purchaseKey
                LIMIT 1
            ];

            if (!String.isBlank(loanKey)) {
                Id resolvedLoanId = resolveLoanId(loanKey);
                if (resolvedLoanId == null) {
                    response.success = false;
                    response.message = 'No loan found for given Loan Id';
                    IntegrationLogUtil.insertLog(serviceName, requestPayload, null, response.message, 'Failed', 404);
                    return response;
                }

                if (isSubvention(transactionType)) {
                    insert new Transcation__c(
                        Purchase_Orders__c = po.Id,
                        Loan__c = resolvedLoanId,
                        Payment__c = paymentReq.paymentReceived,
                        Status__c = 'Received',
                        Transcation_Id__c = paymentReq.transactionId
                    );
                } else {
                    Transcation__c txn = [
                        SELECT Id, Payment__c, Status__c, Transcation_Id__c, Loan__c, Purchase_Orders__c
                        FROM Transcation__c
                        WHERE Purchase_Orders__c = :po.Id
                        AND Loan__c = :resolvedLoanId
                        AND Status__c != 'Received'
                        ORDER BY CreatedDate DESC
                        LIMIT 1
                    ];

                    txn.Payment__c = paymentReq.paymentReceived;
                    txn.Status__c = 'Received';
                    txn.Transcation_Id__c = paymentReq.transactionId;
                    update txn;
                }
            } else {
                Transcation__c txn = [
                    SELECT Id, Payment__c, Status__c, Transcation_Id__c,
                        Purchase_Orders__c,
                        Purchase_Orders__r.Purchase_Order_Id__c,
                        Purchase_Orders__r.Net_Payable_Amount__c,
                        Purchase_Orders__r.Total_Payment_Received__c,
                        Purchase_Orders__r.Lead__c,
                        Purchase_Orders__r.Lead__r.Payment_Received__c
                    FROM Transcation__c
                    WHERE Purchase_Orders__r.Purchase_Order_Id__c = :purchaseKey
                    AND Status__c != 'Received'
                    AND Transcation_Id__c = null
                    AND Payment__c = :paymentReq.paymentReceived
                    LIMIT 1
                ];

                txn.Payment__c = paymentReq.paymentReceived;
                txn.Status__c = 'Received';
                txn.Transcation_Id__c = paymentReq.transactionId;
                update txn;
            }

            AggregateResult ar = [
                SELECT SUM(Payment__c) totalReceived
                FROM Transcation__c
                WHERE Purchase_Orders__c = :po.Id
            ];

            Decimal netPayable = po.Net_Payable_Amount__c == null ? 0 : po.Net_Payable_Amount__c;
            Decimal totalReceived = (Decimal) ar.get('totalReceived');
            totalReceived = totalReceived == null ? 0 : totalReceived;

            String leadStatus;
            if (netPayable > 0 && totalReceived >= netPayable) {
                leadStatus = 'Fully Received';
            } else if (totalReceived > 0) {
                leadStatus = 'Partially Received';
            }

            if (po.Lead__c != null && leadStatus != null) {
                Lead__c leadToUpdate = new Lead__c(Id = po.Lead__c);
                Boolean shouldUpdateLead = false;

                if (!(leadStatus == 'Partially Received' && po.Lead__r.Payment_Received__c == 'Partially Received')) {
                    leadToUpdate.Payment_Received__c = leadStatus;
                    shouldUpdateLead = true;
                }

                if (leadStatus == 'Partially Received') {
                    String targetStage;
                    if (po.Lead__r.Course__c == 'US Pathway') {
                        targetStage = 'U7';
                    } else if (po.Lead__r.Course__c == 'CPA' || po.Lead__r.Course__c == 'CMA' || po.Lead__r.Course__c == 'CAIRA') {
                        targetStage = 'M7';
                    }

                    if (targetStage != null && po.Lead__r.Stage__c != targetStage) {
                        leadToUpdate.Stage__c = targetStage;
                        shouldUpdateLead = true;
                    }
                }

                if (shouldUpdateLead) {
                    update leadToUpdate;
                }
            }

            response.success = true;
            response.message = 'Payment updated successfully';

            IntegrationLogUtil.insertLog(
                serviceName,
                requestPayload,
                truncate(JSON.serialize(response)),
                response.message,
                'Success',
                200
            );
        } catch (QueryException qe) {
            response.success = false;
            response.message = 'No transaction found for given Purchase Id';

            IntegrationLogUtil.insertLog(serviceName, requestPayload, null, response.message, 'Failed', 404);
        } catch (DmlException de) {
            response.success = false;
            response.message = 'DML error while updating payment: ' + de.getMessage();

            IntegrationLogUtil.insertLog(serviceName, requestPayload, null, response.message, 'Failed', 500);
        } catch (Exception e) {
            response.success = false;
            response.message = e.getMessage();

            IntegrationLogUtil.insertLog(serviceName, requestPayload, null, response.message, 'Failed', 500);
        }

        return response;
    }

    global class PaymentRequest {
        public String transactionId;
        public Decimal paymentReceived;
        public String purchaseId;
        public String purchase_id;
        public String loanId;
        public String loan_id;
        public String transactionType;
        public String transaction_type;
    }

    global class ApiResponse {
        public Boolean success;
        public String message;
    }

    private static String truncate(String value) {
        return (value != null && value.length() > 3000)
            ? value.substring(0, 3000)
            : value;
    }

    private static Boolean isSubvention(String transactionType) {
        return !String.isBlank(transactionType) && transactionType.trim().toLowerCase() == 'subvention';
    }

    private static Id resolveLoanId(String loanKey) {
        if (String.isBlank(loanKey)) {
            return null;
        }

        try {
            Id sfLoanId = Id.valueOf(loanKey);
            List<Loan__c> loansBySfId = [SELECT Id FROM Loan__c WHERE Id = :sfLoanId LIMIT 1];
            if (!loansBySfId.isEmpty()) {
                return loansBySfId[0].Id;
            }
        } catch (Exception e) {
            // Fall back to external loan id lookup.
        }

        List<Loan__c> loansByExternalId = [SELECT Id FROM Loan__c WHERE Loan_Id__c = :loanKey LIMIT 1];
        return loansByExternalId.isEmpty() ? null : loansByExternalId[0].Id;
    }
}