force-app/main/default/objects/Course_Enrolled__c/Course_Enrolled__c.object-meta.xml
<CustomObject>
    <label>Course Enrolled</label>
    <nameField>
        <label>Student Enrolled Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Enrolleds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Enrolled__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Course</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Enrolled__c/fields/Stages__c.field-meta.xml
<CustomField>
    <fullName>Stages__c</fullName>
    <label>Stages</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>stages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Enrolled__c/recordTypes/CPA.recordType-meta.xml
<RecordType>
    <fullName>CPA</fullName>
    <active>true</active>
    <label>CPA</label>
</RecordType>

force-app/main/default/globalValueSets/Course.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CMA</fullName>
    </customValue>
    <customValue>
        <fullName>CPA</fullName>
    </customValue>
    <customValue>
        <fullName>CAIRA</fullName>
    </customValue>
    <customValue>
        <fullName>MCOM</fullName>
    </customValue>
    <customValue>
        <fullName>US Pathway</fullName>
    </customValue>
    <masterLabel>Course</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/stages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>M7+</fullName>
        <default>true</default>
        <label>M7+</label>
    </customValue>
    <customValue>
        <fullName>M7#</fullName>
    </customValue>
    <customValue>
        <fullName>M7#-</fullName>
    </customValue>
    <customValue>
        <fullName>M7##</fullName>
    </customValue>
    <customValue>
        <fullName>M8</fullName>
    </customValue>
    <customValue>
        <fullName>M9</fullName>
    </customValue>
    <customValue>
        <fullName>M9+</fullName>
    </customValue>
    <customValue>
        <fullName>M10</fullName>
    </customValue>
    <customValue>
        <fullName>M10+</fullName>
    </customValue>
    <customValue>
        <fullName>M11</fullName>
    </customValue>
    <customValue>
        <fullName>M11+</fullName>
    </customValue>
    <customValue>
        <fullName>M11#</fullName>
    </customValue>
    <customValue>
        <fullName>M12</fullName>
    </customValue>
    <customValue>
        <fullName>M13</fullName>
    </customValue>
    <customValue>
        <fullName>M13+</fullName>
    </customValue>
    <customValue>
        <fullName>M13++</fullName>
    </customValue>
    <customValue>
        <fullName>M13#</fullName>
    </customValue>
    <customValue>
        <fullName>M14</fullName>
    </customValue>
    <customValue>
        <fullName>M14+</fullName>
    </customValue>
    <customValue>
        <fullName>M14++</fullName>
    </customValue>
    <customValue>
        <fullName>M14#</fullName>
    </customValue>
    <customValue>
        <fullName>M15</fullName>
    </customValue>
    <customValue>
        <fullName>M15+</fullName>
    </customValue>
    <customValue>
        <fullName>M15++</fullName>
    </customValue>
    <customValue>
        <fullName>M15#</fullName>
    </customValue>
    <customValue>
        <fullName>M16</fullName>
    </customValue>
    <customValue>
        <fullName>M16+</fullName>
    </customValue>
    <customValue>
        <fullName>M16++</fullName>
    </customValue>
    <customValue>
        <fullName>M16#</fullName>
    </customValue>
    <customValue>
        <fullName>M17</fullName>
    </customValue>
    <masterLabel>stages</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CourseEnrolledTriggerHandle.cls
public class CourseEnrolledTriggerHandle {

    public static void handleAfter(
        List<Course_Enrolled__c> newList,
        Map<Id, Course_Enrolled__c> oldMap
    ) {

        List<Course_Enrolled__c> m7PlusCPARecords = new List<Course_Enrolled__c>();

        for (Course_Enrolled__c ce : newList) {

            Course_Enrolled__c oldCe =
                oldMap != null ? oldMap.get(ce.Id) : null;

            Boolean movedToM7Plus =
                ce.Stages__c == 'M7+' &&
                (oldCe == null || oldCe.Stages__c != 'M7+');

            if (
                ce.Course__c == 'CPA' &&
                movedToM7Plus
            ) {
                m7PlusCPARecords.add(ce);
            }
        }

        if (!m7PlusCPARecords.isEmpty()) {
            CPAScenarioHelper.handleM7Plus(m7PlusCPARecords);
        }
    }
}