force-app/main/default/objects/Course_Enrolled__c/Course_Enrolled__c.object-meta.xml
<CustomObject>
    <label>Course Enrolled</label>
    <nameField>
        <label>Student Enrolled Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Enrolleds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Enrolled__c/fields/CC_Spoc__c.field-meta.xml
<CustomField>
    <fullName>CC_Spoc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CC Spoc</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Course_Enrolleds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrolled__c/fields/Stages__c.field-meta.xml
<CustomField>
    <fullName>Stages__c</fullName>
    <label>Stages</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>stages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_Manager__c/Task_Manager__c.object-meta.xml
<CustomObject>
    <label>Task Manager</label>
    <nameField>
        <label>Task Manager Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Managers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Manager__c/fields/Follow_Up__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up__c</fullName>
    <label>Follow Up</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_Manager__c/fields/Max_Follow_up__c.field-meta.xml
<CustomField>
    <fullName>Max_Follow_up__c</fullName>
    <label>Max Follow up</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task_Manager__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <label>Owner</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Assinged_to</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_Manager__c/fields/Task_Name__c.field-meta.xml
<CustomField>
    <fullName>Task_Name__c</fullName>
    <label>Task Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/globalValueSets/Assinged_to.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CC Spoc</fullName>
    </customValue>
    <customValue>
        <fullName>GP team</fullName>
    </customValue>
    <customValue>
        <fullName>GP Spoc</fullName>
    </customValue>
    <customValue>
        <fullName>SR spoc</fullName>
    </customValue>
    <masterLabel>Assinged to</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/stages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>M7+</fullName>
        <default>true</default>
        <label>M7+</label>
    </customValue>
    <customValue>
        <fullName>M7#</fullName>
    </customValue>
    <customValue>
        <fullName>M7#-</fullName>
    </customValue>
    <customValue>
        <fullName>M7##</fullName>
    </customValue>
    <customValue>
        <fullName>M8</fullName>
    </customValue>
    <customValue>
        <fullName>M9</fullName>
    </customValue>
    <customValue>
        <fullName>M9+</fullName>
    </customValue>
    <customValue>
        <fullName>M10</fullName>
    </customValue>
    <customValue>
        <fullName>M10+</fullName>
    </customValue>
    <customValue>
        <fullName>M11</fullName>
    </customValue>
    <customValue>
        <fullName>M11+</fullName>
    </customValue>
    <customValue>
        <fullName>M11#</fullName>
    </customValue>
    <customValue>
        <fullName>M12</fullName>
    </customValue>
    <customValue>
        <fullName>M13</fullName>
    </customValue>
    <customValue>
        <fullName>M13+</fullName>
    </customValue>
    <customValue>
        <fullName>M13++</fullName>
    </customValue>
    <customValue>
        <fullName>M13#</fullName>
    </customValue>
    <customValue>
        <fullName>M14</fullName>
    </customValue>
    <customValue>
        <fullName>M14+</fullName>
    </customValue>
    <customValue>
        <fullName>M14++</fullName>
    </customValue>
    <customValue>
        <fullName>M14#</fullName>
    </customValue>
    <customValue>
        <fullName>M15</fullName>
    </customValue>
    <customValue>
        <fullName>M15+</fullName>
    </customValue>
    <customValue>
        <fullName>M15++</fullName>
    </customValue>
    <customValue>
        <fullName>M15#</fullName>
    </customValue>
    <customValue>
        <fullName>M16</fullName>
    </customValue>
    <customValue>
        <fullName>M16+</fullName>
    </customValue>
    <customValue>
        <fullName>M16++</fullName>
    </customValue>
    <customValue>
        <fullName>M16#</fullName>
    </customValue>
    <customValue>
        <fullName>M17</fullName>
    </customValue>
    <masterLabel>stages</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CourseEnrolledTriggerHandler.cls
public class CourseEnrolledTriggerHandler {
/*
    public static void afterUpdate(
        List<Course_Enrolled__c> newList,
        Map<Id, Course_Enrolled__c> oldMap
    ) {

        List<Task> tasksToInsert = new List<Task>();
        List<Task> tasksToUpdate = new List<Task>();

        Set<Id> courseIds = new Set<Id>();
        Set<String> stages = new Set<String>();

        
        for (Course_Enrolled__c ce : newList) {
            if (ce.Stages__c != oldMap.get(ce.Id).Stages__c) {
                courseIds.add(ce.Id);
                stages.add(ce.Stages__c);
                stages.add(oldMap.get(ce.Id).Stages__c);
            }
        }

        if (courseIds.isEmpty()) return;

     
        Map<String, Task_Manager__c> configByStage = new Map<String, Task_Manager__c>();
        for (Task_Manager__c cfg : [
            SELECT Stages__c,
                   Task_Name__c,
                   Follow_Up__c,
                   Max_Follow_up__c,
                   Owner__c
            FROM Task_Manager__c
            WHERE Stages__c IN :stages
        ]) {
            configByStage.put(cfg.Stages__c, cfg);
        }

      
        Map<Id, List<Task>> openTasksByCourse = new Map<Id, List<Task>>();

        for (Task t : [
            SELECT Id, Subject, Status, WhatId, OwnerId
            FROM Task
            WHERE WhatId IN :courseIds
            AND Status != 'Completed'
        ]) {
            if (!openTasksByCourse.containsKey(t.WhatId)) {
                openTasksByCourse.put(t.WhatId, new List<Task>());
            }
            openTasksByCourse.get(t.WhatId).add(t);
        }

       
        for (Course_Enrolled__c newRec : newList) {

            Course_Enrolled__c oldRec = oldMap.get(newRec.Id);
            if (newRec.Stages__c == oldRec.Stages__c) continue;

           
            Task_Manager__c oldCfg = configByStage.get(oldRec.Stages__c);
            if (oldCfg != null && openTasksByCourse.containsKey(newRec.Id)) {
                for (Task t : openTasksByCourse.get(newRec.Id)) {
                    if (t.Subject == oldCfg.Task_Name__c) {
                        t.Status = 'Completed';
                        tasksToUpdate.add(t);
                    }
                }
            }

         
            Task_Manager__c newCfg = configByStage.get(newRec.Stages__c);
            if (newCfg == null) continue;

            Task newTask = new Task();
            newTask.Subject = newCfg.Task_Name__c;
            newTask.WhatId = newRec.Id;
            newTask.Status = 'Not Started';
            newTask.Priority = 'High';
            newTask.Description = newCfg.Follow_Up__c;
            newTask.ActivityDate = calculateDueDate(newCfg.Max_Follow_up__c);

          
            if (newCfg.Owner__c == 'CC SPOC' && newRec.CC_Spoc__c != null) {
                newTask.OwnerId = newRec.CC_Spoc__c;
            } else {
                newTask.OwnerId = newRec.OwnerId;
            }

            tasksToInsert.add(newTask);
        }

      
        if (!tasksToUpdate.isEmpty()) update tasksToUpdate;
        if (!tasksToInsert.isEmpty()) insert tasksToInsert;
    }


    private static Date calculateDueDate(String maxFollowUp) {

        if (String.isBlank(maxFollowUp)) return Date.today();

        Integer days = 0;

        if (maxFollowUp.contains('Days')) {
            days = Integer.valueOf(maxFollowUp.replace(' Days', '').trim());
        } 
        else if (maxFollowUp.contains('Hours')) {
            days = 1;
        }

        return Date.today().addDays(days);
    } */
    
    public static void onAfterUpdate(Map<Id, Course_Enrolled__c> newMap, Map<Id, Course_Enrolled__c> oldMap) {
        
    }
}