force-app/main/default/objects/Course_Enrolled__c/Course_Enrolled__c.object-meta.xml
<CustomObject>
    <label>Course Enrolled</label>
    <nameField>
        <label>Student Enrolled Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Enrolleds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Enrolled__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Course</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Enrolled__c/fields/GP_SPOC__c.field-meta.xml
<CustomField>
    <fullName>GP_SPOC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GP SPOC</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Course_Enrolleds1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course_Enrolled__c/fields/Stages__c.field-meta.xml
<CustomField>
    <fullName>Stages__c</fullName>
    <label>Stages</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>stages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Enrolled__c/recordTypes/CMA.recordType-meta.xml
<RecordType>
    <fullName>CMA</fullName>
    <active>true</active>
    <label>CMA</label>
</RecordType>

force-app/main/default/objects/Course_Enrolled__c/recordTypes/CPA.recordType-meta.xml
<RecordType>
    <fullName>CPA</fullName>
    <active>true</active>
    <label>CPA</label>
</RecordType>

force-app/main/default/globalValueSets/Course.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CMA</fullName>
    </customValue>
    <customValue>
        <fullName>CPA</fullName>
    </customValue>
    <customValue>
        <fullName>CAIRA</fullName>
    </customValue>
    <customValue>
        <fullName>MCOM</fullName>
    </customValue>
    <customValue>
        <fullName>US Pathway</fullName>
    </customValue>
    <masterLabel>Course</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/stages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>M7+</fullName>
        <default>true</default>
        <label>M7+</label>
    </customValue>
    <customValue>
        <fullName>M7#</fullName>
    </customValue>
    <customValue>
        <fullName>M7#-</fullName>
    </customValue>
    <customValue>
        <fullName>M7##</fullName>
    </customValue>
    <customValue>
        <fullName>M8</fullName>
    </customValue>
    <customValue>
        <fullName>M9</fullName>
    </customValue>
    <customValue>
        <fullName>M9+</fullName>
    </customValue>
    <customValue>
        <fullName>M10</fullName>
    </customValue>
    <customValue>
        <fullName>M10+</fullName>
    </customValue>
    <customValue>
        <fullName>M11</fullName>
    </customValue>
    <customValue>
        <fullName>M11+</fullName>
    </customValue>
    <customValue>
        <fullName>M11#</fullName>
    </customValue>
    <customValue>
        <fullName>M12</fullName>
    </customValue>
    <customValue>
        <fullName>M13</fullName>
    </customValue>
    <customValue>
        <fullName>M13+</fullName>
    </customValue>
    <customValue>
        <fullName>M13++</fullName>
    </customValue>
    <customValue>
        <fullName>M13#</fullName>
    </customValue>
    <customValue>
        <fullName>M14</fullName>
    </customValue>
    <customValue>
        <fullName>M14+</fullName>
    </customValue>
    <customValue>
        <fullName>M14++</fullName>
    </customValue>
    <customValue>
        <fullName>M14#</fullName>
    </customValue>
    <customValue>
        <fullName>M15</fullName>
    </customValue>
    <customValue>
        <fullName>M15+</fullName>
    </customValue>
    <customValue>
        <fullName>M15++</fullName>
    </customValue>
    <customValue>
        <fullName>M15#</fullName>
    </customValue>
    <customValue>
        <fullName>M16</fullName>
    </customValue>
    <customValue>
        <fullName>M16+</fullName>
    </customValue>
    <customValue>
        <fullName>M16++</fullName>
    </customValue>
    <customValue>
        <fullName>M16#</fullName>
    </customValue>
    <customValue>
        <fullName>M17</fullName>
    </customValue>
    <customValue>
        <fullName>M17+</fullName>
    </customValue>
    <customValue>
        <fullName>M17++</fullName>
    </customValue>
    <customValue>
        <fullName>M17#</fullName>
    </customValue>
    <masterLabel>stages</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CourseEnrolledTriggerHandlerService.cls
public class CourseEnrolledTriggerHandlerService {

    public static void checkAndCreateNewTaskForStatusChange(Map<Id, Course_Enrolled__c> newMap, Map<Id, Course_Enrolled__c> oldMap) {
        List<Course_Enrolled__c> cpaStatusChangedList 	= new List<Course_Enrolled__c>();
        List<Course_Enrolled__c> cmaStatusChangedList 	= new List<Course_Enrolled__c>();
        
        for(Course_Enrolled__c enrolledObj : newMap.values()) {
            if(enrolledObj.Stages__c != oldMap.get(enrolledObj.Id).Stages__c) {
                if(enrolledObj.Course__c == 'CPA') cpaStatusChangedList.add(enrolledObj);
                if(enrolledObj.Course__c == 'CMA') cmaStatusChangedList.add(enrolledObj);   
            }
        }
        
        if(!cpaStatusChangedList.isEmpty()) createCPATasks(cpaStatusChangedList, oldMap);
        if(!cmaStatusChangedList.isEmpty()) createCPATasks(cpaStatusChangedList, oldMap);
    }
    
    
    static void createCPATasks(List<Course_Enrolled__c> cpaStatusChangedList, Map<Id, Course_Enrolled__c> oldMap) {
        List<Task> taskList = new List<Task>();
        String subjectName;
        for(Course_Enrolled__c enrolledObj : cpaStatusChangedList) {
            if(enrolledObj.Stages__c == 'M7+') taskList.add(createTask('Complete Onboarding', enrolledObj.Id, 0, enrolledObj.OwnerId));
//            if(enrolledObj.Stages__c == 'M7#') taskList.add(createTask('Upload docs for Evaluation advice', enrolledObj.Id, 0, enrolledObj.OwnerId));
            if(enrolledObj.Stages__c == 'M7#-') taskList.add(createTask('Upload docs for Evaluation advice', enrolledObj.Id, 0, enrolledObj.OwnerId));
            if(enrolledObj.Stages__c == 'M7##') taskList.add(createTask('Release Evaluation Advice', enrolledObj.Id, 0, enrolledObj.GP_SPOC__c));
            if(enrolledObj.Stages__c == 'M8') taskList.add(createTask('Follow up for payment to Evaluation Agency', enrolledObj.Id, 0, enrolledObj.OwnerId));
            if(enrolledObj.Stages__c == 'M9') taskList.add(createTask('Follow up for Evaluation report', enrolledObj.Id, 0, enrolledObj.OwnerId));
            if(enrolledObj.Stages__c == 'M9+') taskList.add(createTask('Follow up for Evaluation report', enrolledObj.Id, 0, enrolledObj.OwnerId));
            if(enrolledObj.Stages__c == 'M10') taskList.add(createTask('Release NTS Advice', enrolledObj.Id, 0, enrolledObj.GP_SPOC__c));
            if(enrolledObj.Stages__c == 'M10+') taskList.add(createTask('Pay for exam', enrolledObj.Id, 0, enrolledObj.OwnerId));
            if(enrolledObj.Stages__c == 'M11') taskList.add(createTask('Follow up for NTS', enrolledObj.Id, 0, enrolledObj.OwnerId));
            if(enrolledObj.Stages__c == 'M11+') taskList.add(createTask('Exam Scheduling Advice to be released', enrolledObj.Id, 0, enrolledObj.GP_SPOC__c));
            if(enrolledObj.Stages__c == 'M11#') taskList.add(createTask('Schedule Exam and upload pro-metric', enrolledObj.Id, 0, enrolledObj.OwnerId));
            if(enrolledObj.Stages__c == 'M12') taskList.add(createTask('Follow up for exam prep and exam completion', enrolledObj.Id, 0, enrolledObj.OwnerId));
            if(enrolledObj.Stages__c == 'M13') taskList.add(createTask('Follow up for exam result and follow up to request NTS for any other exams', enrolledObj.Id, 0, enrolledObj.OwnerId));
            if(enrolledObj.Stages__c == 'M13+') taskList.add(createTask('Release NTS Advice', enrolledObj.Id, 0, enrolledObj.GP_SPOC__c));
            if(enrolledObj.Stages__c == 'M13++') taskList.add(createTask('Schedule Exam and upload pro-metric', enrolledObj.Id, 0, enrolledObj.OwnerId));
            if(enrolledObj.Stages__c == 'M13#') taskList.add(createTask('Follow up to get exam result', enrolledObj.Id, 0, enrolledObj.OwnerId));
            if(enrolledObj.Stages__c == 'M14') taskList.add(createTask('Follow up for exam result and follow up to request NTS for any other exams', enrolledObj.Id, 0, enrolledObj.OwnerId));
            if(enrolledObj.Stages__c == 'M14+') taskList.add(createTask('Release NTS Advice', enrolledObj.Id, 0, enrolledObj.GP_SPOC__c));
            if(enrolledObj.Stages__c == 'M14++') taskList.add(createTask('Schedule Exam and upload pro-metric', enrolledObj.Id, 0, enrolledObj.OwnerId));
            if(enrolledObj.Stages__c == 'M14#') taskList.add(createTask('Follow up to get exam result', enrolledObj.Id, 0, enrolledObj.OwnerId));
            if(enrolledObj.Stages__c == 'M15') taskList.add(createTask('Follow up for exam result and follow up to request NTS for any other exams', enrolledObj.Id, 0, enrolledObj.OwnerId));
            if(enrolledObj.Stages__c == 'M15+') taskList.add(createTask('Release NTS Advice', enrolledObj.Id, 0, enrolledObj.GP_SPOC__c));
            if(enrolledObj.Stages__c == 'M15++') taskList.add(createTask('Schedule Exam and upload pro-metric', enrolledObj.Id, 0, enrolledObj.OwnerId));
            if(enrolledObj.Stages__c == 'M15#') taskList.add(createTask('Follow up to get exam result', enrolledObj.Id, 0, enrolledObj.OwnerId));
            if(enrolledObj.Stages__c == 'M16') taskList.add(createTask('Follow up for exam result and follow up to request NTS for any other exams', enrolledObj.Id, 0, enrolledObj.OwnerId));
            if(enrolledObj.Stages__c == 'M16+') taskList.add(createTask('Release NTS Advice', enrolledObj.Id, 0, enrolledObj.GP_SPOC__c));
            if(enrolledObj.Stages__c == 'M16++') taskList.add(createTask('Schedule Exam and upload pro-metric', enrolledObj.Id, 0, enrolledObj.OwnerId));
            if(enrolledObj.Stages__c == 'M16#') taskList.add(createTask('Follow up to get exam result', enrolledObj.Id, 0, enrolledObj.OwnerId));
            if(enrolledObj.Stages__c == 'M17') taskList.add(createTask('Follow up for exam result and follow up to request NTS for any other exams', enrolledObj.Id, 0, enrolledObj.OwnerId));
            if(enrolledObj.Stages__c == 'M17+') taskList.add(createTask('Release NTS Advice', enrolledObj.Id, 0, enrolledObj.GP_SPOC__c));
            if(enrolledObj.Stages__c == 'M17++') taskList.add(createTask('Schedule Exam and upload pro-metric', enrolledObj.Id, 0, enrolledObj.OwnerId));
            if(enrolledObj.Stages__c == 'M17#') taskList.add(createTask('Follow up to get exam result', enrolledObj.Id, 0, enrolledObj.OwnerId));
        }                      
    }
    
    
    static void createCMATasks(List<Course_Enrolled__c> cmaStatusChangedList, Map<Id, Course_Enrolled__c> oldMap) {
                      
    }
    
    
    static Task createTask(String subjectName, String recordId, Integer noOfDays, String ownerId) {
        Task newTask = new Task();
        newTask.Subject = subjectName;
        newTask.WhatId = recordId;
        newTask.Status = 'Not Started';
        newTask.Priority = 'High';
        newTask.Description = subjectName;
        newTask.ActivityDate = System.Date.today().addDays(noOfDays);
        newTask.OwnerId = ownerId;
        return newTask;
    }
}