force-app/main/default/objects/Lead/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Course</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Course</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Course.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CMA</fullName>
    </customValue>
    <customValue>
        <fullName>CPA</fullName>
    </customValue>
    <customValue>
        <fullName>CAIRA</fullName>
    </customValue>
    <customValue>
        <fullName>MCOM</fullName>
    </customValue>
    <customValue>
        <fullName>US Pathway</fullName>
    </customValue>
    <masterLabel>Course</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Facebook</fullName>
    </customValue>
    <customValue>
        <fullName>Advertisement</fullName>
    </customValue>
    <customValue>
        <fullName>website-contact_us</fullName>
    </customValue>
    <customValue>
        <fullName>Website</fullName>
    </customValue>
    <customValue>
        <fullName>Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Google Ads</fullName>
    </customValue>
    <customValue>
        <fullName>IVR</fullName>
    </customValue>
    <customValue>
        <fullName>Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Whatsapp Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>WhatsApp BOT on Website</fullName>
    </customValue>
    <customValue>
        <fullName>Live Chat on Website</fullName>
    </customValue>
    <customValue>
        <fullName>SuperBot</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook Ads</fullName>
    </customValue>
    <customValue>
        <fullName>Email Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Miles One App</fullName>
    </customValue>
    <customValue>
        <fullName>Referral - Manual</fullName>
    </customValue>
    <customValue>
        <fullName>Zoom Webinar</fullName>
    </customValue>
    <customValue>
        <fullName>Social</fullName>
    </customValue>
    <customValue>
        <fullName>TimesInternet</fullName>
    </customValue>
    <customValue>
        <fullName>SMS Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Newsletter Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Youtube</fullName>
    </customValue>
    <customValue>
        <fullName>Live Chat</fullName>
    </customValue>
    <customValue>
        <fullName>Incoming Call</fullName>
    </customValue>
    <customValue>
        <fullName>Instagram</fullName>
    </customValue>
    <customValue>
        <fullName>CA-DB</fullName>
    </customValue>
    <customValue>
        <fullName>Blog Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Times Jobs</fullName>
    </customValue>
    <customValue>
        <fullName>Placement Drive</fullName>
    </customValue>
    <customValue>
        <fullName>Naukri</fullName>
    </customValue>
    <masterLabel>Source</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/EligibilityQuickActionController.cls
/**
* @File Name : EligibilityQuickActionController.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : November 27, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | November 27, 2025 |   | Initial Version
**/

public without sharing class EligibilityQuickActionController {

    @AuraEnabled
    public static void initializeEligibility(Id recordId) {
        if (recordId == null) {
            throw new AuraHandledException('Record Id is required.');
        }

        // Assuming this is Lead Id
        List<Lead__c> lead = [
            SELECT Id, OwnerId, City__c, Course__c, Source__c
            FROM Lead__c
            WHERE Id = :recordId
            LIMIT 1
        ];
        String eligibility = 'Eligibility Criteria';
        RoundRobinService.assignForLeads(lead, eligibility);

        EligibilityFolderService.createFoldersForLead(recordId);
    }
}