force-app/main/default/objects/Lead/fields/Source_Bucket__c.field-meta.xml
<CustomField>
    <fullName>Source_Bucket__c</fullName>
    <formula>IF(
    ISPICKVAL( Coming_From__c, &quot;Facebook&quot;) ||
    ISPICKVAL(Coming_From__c, &quot;Advertisement&quot;) ||
    ISPICKVAL(Coming_From__c, &quot;website-contact_us&quot;) ||
    ISPICKVAL(Coming_From__c, &quot;Google Ads&quot;),
    &quot;Bucket 1&quot;,

IF(
    ISPICKVAL(Coming_From__c, &quot;Website&quot;) ||
    ISPICKVAL(Coming_From__c, &quot;Landing Page&quot;),
    &quot;Bucket 2&quot;,

IF(
    ISPICKVAL(Coming_From__c, &quot;Referral&quot;) ||
    ISPICKVAL(Coming_From__c, &quot;Partner&quot;),
    &quot;Bucket 3&quot;,

&quot;Bucket 4&quot;
)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Source Bucket</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Next_Follow_Up_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Follow_Up_Date__c</fullName>
    <label>Next Follow Up Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Queue_Stage__c.field-meta.xml
<CustomField>
    <fullName>Queue_Stage__c</fullName>
    <label>Queue Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Q1</fullName>
            </value>
            <value>
                <fullName>Q2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Source_Bucket__c.field-meta.xml
<CustomField>
    <fullName>Source_Bucket__c</fullName>
    <label>Source Bucket</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Bucket</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Source_Bucket__c/Source_Bucket__c.object-meta.xml
<CustomObject>
    <label>Source Bucket</label>
    <nameField>
        <label>Source Bucket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Source Buckets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Bucket.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bucket 1</fullName>
    </customValue>
    <customValue>
        <fullName>Bucket 2</fullName>
    </customValue>
    <customValue>
        <fullName>Bucket 3</fullName>
    </customValue>
    <customValue>
        <fullName>Bucket 4</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
    </customValue>
    <masterLabel>Bucket</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LeadFollowUpAssignmentBatch.cls
/**
 * Batch class to handle Condition 2:
 * If Stage is Q1 and Next_Follow_Up_Date__c is still empty 
 * till one hour after creation, assign to current user and update Stage to Q2
 */
global class LeadFollowUpAssignmentBatch implements Database.Batchable<SObject>, Schedulable {
    
    // Update with your Public Queue's Developer Name
    private static final String PUBLIC_QUEUE_NAME = 'Public_Queue';
    
    // Batch start method
    global Database.QueryLocator start(Database.BatchableContext bc) {
        Datetime timeLimit = Datetime.now().addMinutes(-60);
        
        String query = 'SELECT Id, OwnerId, Queue_Stage__c, Next_Follow_Up_Date__c ' +
                      'FROM Lead__c ' +
                      'WHERE Queue_Stage__c = \'Q1\' ' +
                      'AND Next_Follow_Up_Date__c = null ' +
                      'AND CreatedDate <= :timeLimit ' +
            		  'AND Source_Bucket__c = \'Bucket 1\' ';
        
        return Database.getQueryLocator(query);
    }
    
    // Batch execute method
    global void execute(Database.BatchableContext bc, List<Lead__c> leads) {
        // Get Queue ID
        List<Group> queues = [SELECT Id FROM Group 
                             WHERE Type = 'Queue' AND DeveloperName = :PUBLIC_QUEUE_NAME 
                             LIMIT 1];
        
        if (queues.isEmpty()) {
            System.debug('Queue not found: ' + PUBLIC_QUEUE_NAME);
            return;
        }
        
        Id queueId = queues[0].Id;
        List<Lead__c> updatedLeads = new List<Lead__c>();
        
        for (Lead__c lead : leads) {
            if (lead.OwnerId != queueId) {
                lead.OwnerId = queueId;
                lead.Queue_Stage__c = 'Q2';
                updatedLeads.add(lead);
            }
        }
        
        if (!updatedLeads.isEmpty()) {
            update updatedLeads;
        }
    }
    
    global void finish(Database.BatchableContext bc) {}
    
    // Schedulable execute method
    global void execute(SchedulableContext sc) {
        Database.executeBatch(new LeadFollowUpAssignmentBatch(), 100);
    }
}