force-app/main/default/objects/Activity_log__c/Activity_log__c.object-meta.xml
<CustomObject>
    <label>Activity log</label>
    <nameField>
        <label>Activity log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity_log__c/fields/Action_Performed_By__c.field-meta.xml
<CustomField>
    <fullName>Action_Performed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Action Performed By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Activity_logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_log__c/fields/Activity_Type__c.field-meta.xml
<CustomField>
    <fullName>Activity_Type__c</fullName>
    <label>Activity Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Call</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Meeting</fullName>
            </value>
            <value>
                <fullName>Level Change</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Enrolment Form</fullName>
            </value>
            <value>
                <fullName>LMS</fullName>
            </value>
            <value>
                <fullName>Lead Merge</fullName>
            </value>
            <value>
                <fullName>View Phone Number</fullName>
            </value>
            <value>
                <fullName>Lead Downgraded</fullName>
            </value>
            <value>
                <fullName>Owner Change</fullName>
            </value>
            <value>
                <fullName>Candidate Lost To Queue</fullName>
            </value>
            <value>
                <fullName>Candidate Assigned From Queue</fullName>
            </value>
            <value>
                <fullName>Enquiry</fullName>
            </value>
            <value>
                <fullName>Gmeet</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity_log__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Activity logs</relationshipLabel>
    <relationshipName>Activity_logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_log__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Activity logs</relationshipLabel>
    <relationshipName>Activity_logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_log__c/fields/Logging_Id__c.field-meta.xml
<CustomField>
    <fullName>Logging_Id__c</fullName>
    <label>Logging Id</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Activity_log__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Activity logs</relationshipLabel>
    <relationshipName>Activity_logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_log__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Activity logs</relationshipLabel>
    <relationshipName>Activity_logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_log__c/fields/Transcation__c.field-meta.xml
<CustomField>
    <fullName>Transcation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transcation</label>
    <referenceTo>Transcation__c</referenceTo>
    <relationshipLabel>Activity logs</relationshipLabel>
    <relationshipName>Activity_logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_log__c/fields/Transcation_Amount__c.field-meta.xml
<CustomField>
    <fullName>Transcation_Amount__c</fullName>
    <label>Transcation Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Activity_log__c/fields/Transcation_Status__c.field-meta.xml
<CustomField>
    <fullName>Transcation_Status__c</fullName>
    <label>Transcation Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Initiated</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity_log__c/recordTypes/Payment.recordType-meta.xml
<RecordType>
    <fullName>Payment</fullName>
    <active>true</active>
    <label>Payment</label>
</RecordType>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO -{0000}</displayFormat>
        <label>Purchase Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Confirmed,</fullName>
            </value>
            <value>
                <fullName>Paid,</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transcation__c/Transcation__c.object-meta.xml
<CustomObject>
    <label>Transcation</label>
    <nameField>
        <displayFormat>Transcation-{0000}</displayFormat>
        <label>Transcation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transcations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transcation__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <label>Payment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transcation__c/fields/Purchase_Orders__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Orders__c</fullName>
    <label>Purchase Orders</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Transcations (Purchase Orders)</relationshipLabel>
    <relationshipName>Transcations1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transcation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Initiated</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TranscationTriggerHandler.cls
/*
    Author       : Rohit Singh Bisht
*/
public class TranscationTriggerHandler {

    public static Boolean isFirstRun = true;

    public static void createActivityLogs(List<Transcation__c> newList, Map<Id, Transcation__c> oldMap) {

        if(!isFirstRun) return;
        isFirstRun = false;

        List<Activity_Log__c> activityList = new List<Activity_Log__c>();

        // Record Type 
        Id paymentRecordTypeId = Schema.SObjectType.Activity_Log__c
            .getRecordTypeInfosByDeveloperName()
            .get('Payment')
            .getRecordTypeId();

        Set<Id> poIds = new Set<Id>();

        for(Transcation__c trans : newList){
            if(trans.Purchase_Orders__c != null){
                poIds.add(trans.Purchase_Orders__c);
            }
        }

        Map<Id, Purchase_Order__c> poMap = new Map<Id, Purchase_Order__c>();

        if(!poIds.isEmpty()){
            poMap = new Map<Id, Purchase_Order__c>([
                SELECT Id, Lead__c, Candidate__c, Student__c
                FROM Purchase_Order__c
                WHERE Id IN :poIds
            ]);
        }

      
        for(Transcation__c trans : newList) {

          
            Boolean isInsert = (oldMap == null);
            Boolean isStatusChanged = false;
            Boolean isPaymentChanged = false;

            String oldStatus = '';
            Decimal oldPayment = 0;

            if(oldMap != null && oldMap.containsKey(trans.Id)) {
                Transcation__c oldRec = oldMap.get(trans.Id);

                //  Status Change
                if(String.valueOf(oldRec.Status__c) != String.valueOf(trans.Status__c)) {
                    isStatusChanged = true;
                    oldStatus = oldRec.Status__c;
                }

                // Payment Change
                if(oldRec.Payment__c != trans.Payment__c) {
                    isPaymentChanged = true;
                    oldPayment = oldRec.Payment__c;
                }
            }

            if(isInsert || isStatusChanged || isPaymentChanged) {

                Activity_Log__c log = new Activity_Log__c();

                //Basic Fields
                log.Name = 'Transaction Log - ' + trans.Name;
                log.RecordTypeId = paymentRecordTypeId;
                log.Transcation__c = trans.Id;
                log.Transcation_Amount__c = trans.Payment__c;
                log.Transcation_Status__c = trans.Status__c;
                log.Action_Performed_By__c = UserInfo.getUserId();
                log.Logging_Id__c = 'LOG-' + trans.Id + '-' + System.currentTimeMillis();
                log.Activity_Type__c = 'Payment';

                if(trans.Purchase_Orders__c != null){

                    log.Purchase_Order__c = trans.Purchase_Orders__c;

                    Purchase_Order__c po = poMap.get(trans.Purchase_Orders__c);

                    if(po != null){
                        log.Lead__c = po.Lead__c;
                        log.Candidate__c = po.Candidate__c;
                        log.Student__c = po.Student__c;
                    }
                }

                if(isInsert){
                    log.Description__c = 'Transaction created with status: ' + trans.Status__c +
                                         ' and amount: ' + trans.Payment__c;
                }
                else if(isStatusChanged && isPaymentChanged){
                    log.Description__c = 'Status changed from ' + oldStatus + ' to ' + trans.Status__c +
                                         ' and Payment changed from ' + oldPayment + ' to ' + trans.Payment__c;
                }
                else if(isStatusChanged){
                    log.Description__c = 'Status changed from ' + oldStatus + ' to ' + trans.Status__c;
                }
                else if(isPaymentChanged){
                    log.Description__c = 'Payment changed from ' + oldPayment + ' to ' + trans.Payment__c;
                }

                activityList.add(log);
            }
        }

        if(!activityList.isEmpty()){
            ActivityLogService.insertLogs(activityList);
        }
    }
}