force-app/main/default/objects/Activity_log__c/Activity_log__c.object-meta.xml
<CustomObject>
    <label>Activity log</label>
    <nameField>
        <label>Activity log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity_log__c/fields/Action_Performed_By__c.field-meta.xml
<CustomField>
    <fullName>Action_Performed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Action Performed By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Activity_logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_log__c/fields/Activity_Type__c.field-meta.xml
<CustomField>
    <fullName>Activity_Type__c</fullName>
    <label>Activity Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Call</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Meeting</fullName>
            </value>
            <value>
                <fullName>Level Change</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Enrolment Form</fullName>
            </value>
            <value>
                <fullName>LMS</fullName>
            </value>
            <value>
                <fullName>Lead Merge</fullName>
            </value>
            <value>
                <fullName>View Phone Number</fullName>
            </value>
            <value>
                <fullName>Lead Downgraded</fullName>
            </value>
            <value>
                <fullName>Owner Change</fullName>
            </value>
            <value>
                <fullName>Candidate Lost To Queue</fullName>
            </value>
            <value>
                <fullName>Candidate Assigned From Queue</fullName>
            </value>
            <value>
                <fullName>Enquiry</fullName>
            </value>
            <value>
                <fullName>Gmeet</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity_log__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Activity logs</relationshipLabel>
    <relationshipName>Activity_logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_log__c/fields/Logging_Id__c.field-meta.xml
<CustomField>
    <fullName>Logging_Id__c</fullName>
    <label>Logging Id</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Activity_log__c/fields/New_Owner__c.field-meta.xml
<CustomField>
    <fullName>New_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Activity_logs2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_log__c/fields/Previous_Owner__c.field-meta.xml
<CustomField>
    <fullName>Previous_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Previous Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Activity_logs1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval_Process__c/Approval_Process__c.object-meta.xml
<CustomObject>
    <label>Approval Process</label>
    <nameField>
        <displayFormat>MR-{000}</displayFormat>
        <label>Merge Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Approval_Process__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Merge_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval_Process__c/fields/Master_Lead__c.field-meta.xml
<CustomField>
    <fullName>Master_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Merge_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval_Process__c/fields/Merge_Status__c.field-meta.xml
<CustomField>
    <fullName>Merge_Status__c</fullName>
    <label>Merge Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approval_Process__c/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <label>Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lead Transfer</fullName>
            </value>
            <value>
                <fullName>Lead Merge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approval_Process__c/fields/Requestor__c.field-meta.xml
<CustomField>
    <fullName>Requestor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requestor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Merge_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval_Process__c/recordTypes/Lead_Transfer_Request.recordType-meta.xml
<RecordType>
    <fullName>Lead_Transfer_Request</fullName>
    <active>true</active>
    <label>Lead Transfer Request</label>
</RecordType>

force-app/main/default/objects/Lead/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LeadTransferController.cls
public with sharing class LeadTransferController {

    @AuraEnabled
    public static void sendApproval(Id leadId, String comments) {

        Id currentUserId = UserInfo.getUserId();
        Lead ld = [SELECT Id, OwnerId FROM Lead WHERE Id = :leadId LIMIT 1];
        
         if (ld.OwnerId == currentUserId) {
            throw new AuraHandledException('You cannot send request for your own lead.');
        }

        // Fetch Managers for both Lead Owner and current Requestor
        Set<Id> userIds = new Set<Id>{ld.OwnerId, currentUserId};
        Map<Id, User> userMap = new Map<Id, User>([SELECT Id, ManagerId FROM User WHERE Id IN :userIds]);

        User leadOwner = userMap.get(ld.OwnerId);
        User requestor = userMap.get(currentUserId);

        Id approverId = '005C1000005Qn8fIAC'; // Fallback Admin ID

        if (leadOwner != null && requestor != null && 
            leadOwner.ManagerId != null && leadOwner.ManagerId == requestor.ManagerId) {
            approverId = leadOwner.ManagerId;
        }

        Id recordTypeId = Schema.SObjectType.Approval_Process__c.getRecordTypeInfosByDeveloperName().get('Lead_Transfer_Request').getRecordTypeId();

        Approval_Process__c req = new Approval_Process__c();

        req.Master_Lead__c = leadId;
        req.Requestor__c = currentUserId;
        req.Approver__c = approverId;
        req.OwnerId = approverId;
        req.Comments__c = comments;
        req.Merge_Status__c = 'Pending';
        req.Record_Type__c = 'Lead Transfer';
        req.RecordTypeId = recordTypeId;

        insert req;

        // CREATE INITIAL LOG
        insert new Activity_log__c(
            Name = 'Lead Transfer Request',
            Candidate__c = leadId,
            Activity_Type__c = 'Owner Change',
            Description__c = 'Lead Transfer Request initiated. Status: Pending approval.',
            Previous_Owner__c = ld.OwnerId,
            New_Owner__c = currentUserId,
            Logging_Id__c = req.Id,
            Action_Performed_By__c = currentUserId
        );
    }
}