force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO -{0000}</displayFormat>
        <label>Purchase Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/fields/Net_Payable_Amount__c.field-meta.xml
<CustomField>
    <fullName>Net_Payable_Amount__c</fullName>
    <formula>Total_Amount__c - Discount_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Net Payable Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Confirmed,</fullName>
            </value>
            <value>
                <fullName>Paid,</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transcation__c/Transcation__c.object-meta.xml
<CustomObject>
    <label>Transcation</label>
    <nameField>
        <displayFormat>Transcation-{0000}</displayFormat>
        <label>Transcation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transcations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transcation__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <label>Payment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transcation__c/fields/Purchase_Orders__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Orders__c</fullName>
    <label>Purchase Orders</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Transcations (Purchase Orders)</relationshipLabel>
    <relationshipName>Transcations1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transcation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Initiated</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TransactionPaymentService.cls
public without sharing class TransactionPaymentService {

    @AuraEnabled
    public static void saveDownPayment(Id purchaseOrderId, Decimal amount) {

        if (purchaseOrderId == null || amount == null || amount <= 0) {
            throw new AuraHandledException('Invalid input');
        }

        // Get Purchase Order Net Payable Amount
        Purchase_Order__c po = [
            SELECT Id, Net_Payable_Amount__c
            FROM Purchase_Order__c
            WHERE Id = :purchaseOrderId
            LIMIT 1
        ];

        if (po.Net_Payable_Amount__c == null || po.Net_Payable_Amount__c <= 0) {
            throw new AuraHandledException('Net payable amount is not defined.');
        }

        //  Get last transaction to calculate running total
        List<Transcation__c> lastTxn = [
            SELECT Payment_Received__c
            FROM Transcation__c
            WHERE Purchase_Orders__c = :purchaseOrderId
            ORDER BY CreatedDate DESC
            LIMIT 1
        ];

        Decimal previousTotal = 0;
        if (!lastTxn.isEmpty() && lastTxn[0].Payment_Received__c != null) {
            previousTotal = lastTxn[0].Payment_Received__c;
        }

        Decimal newTotal = previousTotal + amount;

        // VALIDATION: total payment should not exceed net payable
        if (newTotal > po.Net_Payable_Amount__c) {
            throw new AuraHandledException(
                'Down payment exceeds the net payable amount. Remaining payable is ₹'
                + (po.Net_Payable_Amount__c - previousTotal)
            );
        }

        //  Always create NEW transaction
        Transcation__c newTxn = new Transcation__c();
        newTxn.Purchase_Orders__c  = purchaseOrderId;
        newTxn.Payment__c          = amount;          
        // newTxn.Payment_Received__c = newTotal;        
        newTxn.Status__c           = 'Initiated';

        insert newTxn;

        Callout_PaymentUpdateApi.sendPaymentUpdate
            (
            purchaseOrderId,
            amount
        );
        
    }
}