force-app/main/default/objects/Enquiry__c/Enquiry__c.object-meta.xml
<CustomObject>
    <label>Enquiry</label>
    <nameField>
        <label>Enquiry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enquiries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enquiry__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Enquiries</relationshipLabel>
    <relationshipName>Enquiries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Untracked</fullName>
            </value>
            <value>
                <fullName>Tracked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>M_Stages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/M_Stages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>M1</fullName>
    </customValue>
    <customValue>
        <fullName>M2</fullName>
    </customValue>
    <customValue>
        <fullName>M3</fullName>
    </customValue>
    <customValue>
        <fullName>M3+</fullName>
    </customValue>
    <customValue>
        <fullName>M3++</fullName>
    </customValue>
    <customValue>
        <fullName>M4-</fullName>
    </customValue>
    <customValue>
        <fullName>M4</fullName>
    </customValue>
    <customValue>
        <fullName>M5</fullName>
    </customValue>
    <customValue>
        <fullName>M6</fullName>
    </customValue>
    <customValue>
        <fullName>M7</fullName>
    </customValue>
    <customValue>
        <fullName>M7+</fullName>
    </customValue>
    <customValue>
        <fullName>B1</fullName>
    </customValue>
    <customValue>
        <fullName>B2</fullName>
    </customValue>
    <customValue>
        <fullName>B3</fullName>
    </customValue>
    <customValue>
        <fullName>B3+</fullName>
    </customValue>
    <customValue>
        <fullName>B3++</fullName>
    </customValue>
    <customValue>
        <fullName>B4-</fullName>
    </customValue>
    <customValue>
        <fullName>B4</fullName>
    </customValue>
    <customValue>
        <fullName>B5</fullName>
    </customValue>
    <customValue>
        <fullName>B6</fullName>
    </customValue>
    <customValue>
        <fullName>B7</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
    </customValue>
    <customValue>
        <fullName>M7#</fullName>
    </customValue>
    <customValue>
        <fullName>U1</fullName>
    </customValue>
    <customValue>
        <fullName>U2</fullName>
    </customValue>
    <customValue>
        <fullName>U3</fullName>
    </customValue>
    <customValue>
        <fullName>U3+</fullName>
    </customValue>
    <customValue>
        <fullName>U3++</fullName>
    </customValue>
    <customValue>
        <fullName>U4-</fullName>
    </customValue>
    <customValue>
        <fullName>U4</fullName>
    </customValue>
    <masterLabel>M Stages</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TableauScriptsTest.cls
public with sharing class TableauScriptsTest {
    
    
    
    public static void testTableauScripts() {
        
        Set<Id> LeadIds = new Set<Id>();
        
        for(Enquiry__C enq : [Select Lead__c from Enquiry__c where ownerId!= null] ){
            LeadIds.add(enq.Lead__c);
        }
        
        List<AggregateResult> LeadList = [Select Count_distinct(Id) totalCount from Lead__c where id in: LeadIds and Stage__c  In ('M7+','M7') and ownerId != null];
        
        
        Integer leadCount = (Integer) leadList[0].get('totalCount');
        System.debug('Lead Count = ' + leadCount);
        


        
    }
    
    
    
    
}