force-app/main/default/objects/Enquiry__c/Enquiry__c.object-meta.xml
<CustomObject>
    <label>Enquiry</label>
    <nameField>
        <label>Enquiry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enquiries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Enquiry__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Enquiries</relationshipLabel>
    <relationshipName>Enquiries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Coming_From__c.field-meta.xml
<CustomField>
    <fullName>Coming_From__c</fullName>
    <label>Coming From</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>website-contact_us</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Enquiries</relationshipLabel>
    <relationshipName>Enquiries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Untracked</fullName>
            </value>
            <value>
                <fullName>Tracked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enquiry__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enquiries</relationshipLabel>
    <relationshipName>Enquiries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Coming_From__c.field-meta.xml
<CustomField>
    <fullName>Coming_From__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>M_Stages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/recordTypes/CAIRA.recordType-meta.xml
<RecordType>
    <fullName>CAIRA</fullName>
    <active>true</active>
    <label>CAIRA</label>
</RecordType>

force-app/main/default/objects/Webinar__c/Webinar__c.object-meta.xml
<CustomObject>
    <label>Webinar</label>
    <nameField>
        <label>Webinar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Webinars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Webinar__c/fields/Type_Of_Webinar__c.field-meta.xml
<CustomField>
    <fullName>Type_Of_Webinar__c</fullName>
    <label>Type Of Webinar</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webinar_Member__c/Webinar_Member__c.object-meta.xml
<CustomObject>
    <label>Webinar Member</label>
    <nameField>
        <displayFormat>W Member - {0000}</displayFormat>
        <label>Webinar Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Webinar Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Webinar_Member__c/fields/Attendance_Status__c.field-meta.xml
<CustomField>
    <fullName>Attendance_Status__c</fullName>
    <label>Attendance Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Present</fullName>
            </value>
            <value>
                <fullName>Absent</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Webinar_Member__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Webinar Members</relationshipLabel>
    <relationshipName>Webinar_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Webinar_Member__c/fields/Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Enquiry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry</label>
    <referenceTo>Enquiry__c</referenceTo>
    <relationshipLabel>Webinar Members</relationshipLabel>
    <relationshipName>Webinar_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Webinar_Member__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Webinar Members</relationshipLabel>
    <relationshipName>Webinar_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Webinar_Member__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Webinar Members</relationshipLabel>
    <relationshipName>Webinar_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Webinar_Member__c/fields/Webinar__c.field-meta.xml
<CustomField>
    <fullName>Webinar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Webinar</label>
    <referenceTo>Webinar__c</referenceTo>
    <relationshipLabel>Webinar Members</relationshipLabel>
    <relationshipName>Webinar_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/M_Stages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>M1</fullName>
    </customValue>
    <customValue>
        <fullName>M2</fullName>
    </customValue>
    <customValue>
        <fullName>M3</fullName>
    </customValue>
    <customValue>
        <fullName>M3+</fullName>
    </customValue>
    <customValue>
        <fullName>M3++</fullName>
    </customValue>
    <customValue>
        <fullName>M4-</fullName>
    </customValue>
    <customValue>
        <fullName>M4</fullName>
    </customValue>
    <customValue>
        <fullName>M5</fullName>
    </customValue>
    <customValue>
        <fullName>M6</fullName>
    </customValue>
    <customValue>
        <fullName>M7</fullName>
    </customValue>
    <customValue>
        <fullName>M7+</fullName>
    </customValue>
    <customValue>
        <fullName>B1</fullName>
    </customValue>
    <customValue>
        <fullName>B2</fullName>
    </customValue>
    <customValue>
        <fullName>B3</fullName>
    </customValue>
    <customValue>
        <fullName>B3+</fullName>
    </customValue>
    <customValue>
        <fullName>B3++</fullName>
    </customValue>
    <customValue>
        <fullName>B4-</fullName>
    </customValue>
    <customValue>
        <fullName>B4</fullName>
    </customValue>
    <customValue>
        <fullName>B5</fullName>
    </customValue>
    <customValue>
        <fullName>B6</fullName>
    </customValue>
    <customValue>
        <fullName>B7</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
    </customValue>
    <customValue>
        <fullName>M7#</fullName>
    </customValue>
    <customValue>
        <fullName>U1</fullName>
    </customValue>
    <customValue>
        <fullName>U2</fullName>
    </customValue>
    <customValue>
        <fullName>U3</fullName>
    </customValue>
    <customValue>
        <fullName>U3+</fullName>
    </customValue>
    <customValue>
        <fullName>U3++</fullName>
    </customValue>
    <customValue>
        <fullName>U4-</fullName>
    </customValue>
    <customValue>
        <fullName>U4</fullName>
    </customValue>
    <masterLabel>M Stages</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Facebook</fullName>
    </customValue>
    <customValue>
        <fullName>Advertisement</fullName>
    </customValue>
    <customValue>
        <fullName>website-contact_us</fullName>
    </customValue>
    <customValue>
        <fullName>Website</fullName>
    </customValue>
    <customValue>
        <fullName>Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Google Ads</fullName>
    </customValue>
    <customValue>
        <fullName>IVR</fullName>
    </customValue>
    <customValue>
        <fullName>Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Whatsapp Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>WhatsApp BOT on Website</fullName>
    </customValue>
    <customValue>
        <fullName>Live Chat on Website</fullName>
    </customValue>
    <customValue>
        <fullName>SuperBot</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook Ads</fullName>
    </customValue>
    <customValue>
        <fullName>Email Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Miles One App</fullName>
    </customValue>
    <customValue>
        <fullName>Referral - Manual</fullName>
    </customValue>
    <customValue>
        <fullName>Zoom Webinar</fullName>
    </customValue>
    <customValue>
        <fullName>Social</fullName>
    </customValue>
    <customValue>
        <fullName>TimesInternet</fullName>
    </customValue>
    <customValue>
        <fullName>SMS Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Newsletter Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Youtube</fullName>
    </customValue>
    <customValue>
        <fullName>Live Chat</fullName>
    </customValue>
    <customValue>
        <fullName>Incoming Call</fullName>
    </customValue>
    <customValue>
        <fullName>Instagram</fullName>
    </customValue>
    <customValue>
        <fullName>CA-DB</fullName>
    </customValue>
    <customValue>
        <fullName>Blog Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Times Jobs</fullName>
    </customValue>
    <customValue>
        <fullName>Placement Drive</fullName>
    </customValue>
    <customValue>
        <fullName>Naukri</fullName>
    </customValue>
    <masterLabel>Source</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SobjectNavBarController.cls
public without sharing class SobjectNavBarController {

    private static final String SOURCE_CAIRA_WEBINAR = 'CAIRA Webinar';
    private static final String SOURCE_ZOOM_WEBINAR = 'Zoom Webinar';

    @AuraEnabled(cacheable=true)
    public static NavDataWrapper getNavData(Id recordId) {
        NavDataWrapper res = new NavDataWrapper();
        res.enquiry = new List<SourceCountWrapper>();
        res.latestSource = 'Sources';

        if (recordId == null) {
            System.debug(LoggingLevel.WARN, 'getNavData: recordId is null');
            return res;
        }

        String sObjName = recordId.getSObjectType().getDescribe().getName();
        Boolean isLead = (sObjName == 'Lead__c');
        Boolean isAccount = (sObjName == 'Account');
        Boolean isCandidate = (sObjName == 'Lead');
        if (!isLead && !isAccount && !isCandidate) {
            System.debug(LoggingLevel.WARN, 'getNavData: Unsupported sObjectType=' + sObjName + ', recordId=' + recordId);
            return res;
        }

        System.debug(LoggingLevel.INFO, 'getNavData: recordId=' + recordId + ', sObjName=' + sObjName);

        Map<String, SourceCountWrapper> sourceMap = new Map<String, SourceCountWrapper>();

        if (isLead) {
            mergeCounts(sourceMap, getEnquirySourcesByLead(recordId));
            mergeCounts(sourceMap, getEventSources(recordId));
            mergeCounts(sourceMap, getWebinarSourcesByLead(recordId));
        } else if (isAccount) {
            mergeCounts(sourceMap, getEnquirySourcesByStudent(recordId));
            mergeCounts(sourceMap, getEventSources(recordId));
            mergeCounts(sourceMap, getWebinarSourcesByStudent(recordId));
        } else if (isCandidate) {
            mergeCounts(sourceMap, getEnquirySourcesByCandidate(recordId));
            mergeCounts(sourceMap, getEventSources(recordId));
            mergeCounts(sourceMap, getWebinarSourcesByCandidate(recordId));
        }

        res.enquiry = sourceMap.values();
        res.enquiry.sort();

        Datetime latestDt;
        String latestSrc;

        for (SourceCountWrapper w : res.enquiry) {
            if (w != null && w.lastModified != null && (latestDt == null || w.lastModified > latestDt)) {
                latestDt = w.lastModified;
                latestSrc = w.source;
            }
        }

        if (!String.isBlank(latestSrc)) res.latestSource = latestSrc;

        System.debug(LoggingLevel.INFO, 'getNavData: latestSource=' + res.latestSource + ', enquiryTabs=' + res.enquiry.size());
        return res;
    }

    private static List<SourceCountWrapper> getEnquirySourcesByLead(Id recordId) {
        List<SourceCountWrapper> outList = new List<SourceCountWrapper>();
        for (AggregateResult ar : [
            SELECT Coming_From__c source, COUNT(Id) recordCount, MAX(LastModifiedDate) latestDt
            FROM Enquiry__c
            WHERE Lead__c = :recordId AND Coming_From__c != null AND Coming_From__c != ''
            GROUP BY Coming_From__c
            ORDER BY MAX(LastModifiedDate) DESC
        ]) {
            outList.add(new SourceCountWrapper((String) ar.get('source'), (Integer) ar.get('recordCount'), (Datetime) ar.get('latestDt')));
        }
        return outList;
    }

    private static List<SourceCountWrapper> getEnquirySourcesByStudent(Id recordId) {
        List<SourceCountWrapper> outList = new List<SourceCountWrapper>();
        for (AggregateResult ar : [
            SELECT Coming_From__c source, COUNT(Id) recordCount, MAX(LastModifiedDate) latestDt
            FROM Enquiry__c
            WHERE Student__c = :recordId AND Coming_From__c != null AND Coming_From__c != ''
            GROUP BY Coming_From__c
            ORDER BY MAX(LastModifiedDate) DESC
        ]) {
            outList.add(new SourceCountWrapper((String) ar.get('source'), (Integer) ar.get('recordCount'), (Datetime) ar.get('latestDt')));
        }
        return outList;
    }

    private static List<SourceCountWrapper> getEnquirySourcesByCandidate(Id recordId) {
        List<SourceCountWrapper> outList = new List<SourceCountWrapper>();
        for (AggregateResult ar : [
            SELECT Coming_From__c source, COUNT(Id) recordCount, MAX(LastModifiedDate) latestDt
            FROM Enquiry__c
            WHERE Candidate__c = :recordId AND Coming_From__c != null AND Coming_From__c != ''
            GROUP BY Coming_From__c
            ORDER BY MAX(LastModifiedDate) DESC
        ]) {
            outList.add(new SourceCountWrapper((String) ar.get('source'), (Integer) ar.get('recordCount'), (Datetime) ar.get('latestDt')));
        }
        return outList;
    }

    private static List<SourceCountWrapper> getEventSources(Id recordId) {
        List<SourceCountWrapper> outList = new List<SourceCountWrapper>();
        for (AggregateResult ar : [
            SELECT Meeting_type__c source, COUNT(Id) recordCount, MAX(LastModifiedDate) latestDt
            FROM Event
            WHERE (WhoId = :recordId OR WhatId = :recordId) AND Meeting_type__c != null AND Meeting_type__c != '' AND Stage__c = 'Completed'
            GROUP BY Meeting_type__c
            ORDER BY MAX(LastModifiedDate) DESC
        ]) {
            outList.add(new SourceCountWrapper((String) ar.get('source'), (Integer) ar.get('recordCount'), (Datetime) ar.get('latestDt')));
        }
        return outList;
    }

    private static List<SourceCountWrapper> getWebinarSourcesByLead(Id recordId) {
        List<SourceCountWrapper> outList = new List<SourceCountWrapper>();
        for (AggregateResult ar : [
            SELECT Webinar__r.Type_Of_Webinar__c webinarType, COUNT(Id) recordCount, MAX(LastModifiedDate) latestDt
            FROM Webinar_Member__c
            WHERE Lead__c = :recordId AND Webinar__c != null AND Attendance_Status__c = 'Present'
            GROUP BY Webinar__r.Type_Of_Webinar__c
            ORDER BY MAX(LastModifiedDate) DESC
        ]) {
            outList.add(new SourceCountWrapper(getWebinarSourceLabel((String) ar.get('webinarType')), (Integer) ar.get('recordCount'), (Datetime) ar.get('latestDt')));
        }
        return outList;
    }

    private static List<SourceCountWrapper> getWebinarSourcesByStudent(Id recordId) {
        List<SourceCountWrapper> outList = new List<SourceCountWrapper>();
        for (AggregateResult ar : [
            SELECT Webinar__r.Type_Of_Webinar__c webinarType, COUNT(Id) recordCount, MAX(LastModifiedDate) latestDt
            FROM Webinar_Member__c
            WHERE Student__c = :recordId AND Webinar__c != null AND Attendance_Status__c = 'Present'
            GROUP BY Webinar__r.Type_Of_Webinar__c
            ORDER BY MAX(LastModifiedDate) DESC
        ]) {
            outList.add(new SourceCountWrapper(getWebinarSourceLabel((String) ar.get('webinarType')), (Integer) ar.get('recordCount'), (Datetime) ar.get('latestDt')));
        }
        return outList;
    }

    private static List<SourceCountWrapper> getWebinarSourcesByCandidate(Id recordId) {
        List<SourceCountWrapper> outList = new List<SourceCountWrapper>();
        for (AggregateResult ar : [
            SELECT Webinar__r.Type_Of_Webinar__c webinarType, COUNT(Id) recordCount, MAX(LastModifiedDate) latestDt
            FROM Webinar_Member__c
            WHERE Candidate__c = :recordId AND Webinar__c != null AND Attendance_Status__c = 'Present'
            GROUP BY Webinar__r.Type_Of_Webinar__c
            ORDER BY MAX(LastModifiedDate) DESC
        ]) {
            outList.add(new SourceCountWrapper(getWebinarSourceLabel((String) ar.get('webinarType')), (Integer) ar.get('recordCount'), (Datetime) ar.get('latestDt')));
        }
        return outList;
    }

    private static void mergeCounts(Map<String, SourceCountWrapper> sourceMap, List<SourceCountWrapper> items) {
        for (SourceCountWrapper item : items) {
            if (item == null || String.isBlank(item.source)) {
                continue;
            }

            if (!sourceMap.containsKey(item.source)) {
                sourceMap.put(item.source, new SourceCountWrapper(item.source, item.count, item.lastModified));
                continue;
            }

            SourceCountWrapper existing = sourceMap.get(item.source);
            existing.count += item.count == null ? 0 : item.count;
            if (item.lastModified != null && (existing.lastModified == null || item.lastModified > existing.lastModified)) {
                existing.lastModified = item.lastModified;
            }
        }
    }

    private static String getWebinarSourceLabel(String webinarType) {
        return webinarType != null && webinarType.trim().equalsIgnoreCase('CAIRA')
            ? SOURCE_CAIRA_WEBINAR
            : SOURCE_ZOOM_WEBINAR;
    }

    public class NavDataWrapper {
        @AuraEnabled public List<SourceCountWrapper> enquiry;
        @AuraEnabled public String latestSource;
    }

    public class SourceCountWrapper implements Comparable {
        @AuraEnabled public String source;
        @AuraEnabled public Integer count;
        @AuraEnabled public Datetime lastModified;

        public SourceCountWrapper(String source, Integer count, Datetime lastModified) {
            this.source = source;
            this.count = count;
            this.lastModified = lastModified;
        }

        public Integer compareTo(Object obj) {
            SourceCountWrapper other = (SourceCountWrapper) obj;
            if (other == null) return -1;
            if (this.lastModified == other.lastModified) return 0;
            if (this.lastModified == null) return 1;
            if (other.lastModified == null) return -1;
            return this.lastModified > other.lastModified ? -1 : 1;
        }
    }
}