force-app/main/default/objects/Bucket_Mapping__c/Bucket_Mapping__c.object-meta.xml
<CustomObject>
    <label>Bucket Mapping</label>
    <nameField>
        <displayFormat>Bucket Mapping - {0000}</displayFormat>
        <label>Bucket Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bucket Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bucket_Mapping__c/fields/Bucket__c.field-meta.xml
<CustomField>
    <fullName>Bucket__c</fullName>
    <label>Bucket</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bucket 1</fullName>
            </value>
            <value>
                <fullName>Bucket 2</fullName>
            </value>
            <value>
                <fullName>Bucket 3</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
            <value>
                <fullName>Accounting Vertical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bucket_Mapping__c/fields/Course_Values__c.field-meta.xml
<CustomField>
    <fullName>Course_Values__c</fullName>
    <label>Course Values</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Course</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bucket_Mapping__c/fields/Source_Values__c.field-meta.xml
<CustomField>
    <fullName>Source_Values__c</fullName>
    <label>Source Values</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bucket_Mapping__c/fields/Value_Type__c.field-meta.xml
<CustomField>
    <fullName>Value_Type__c</fullName>
    <label>Value Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Course</fullName>
            </value>
            <value>
                <fullName>Source</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bucket_Mapping__c/recordTypes/Course.recordType-meta.xml
<RecordType>
    <fullName>Course</fullName>
    <active>true</active>
    <label>Course</label>
</RecordType>

force-app/main/default/objects/Bucket_Mapping__c/recordTypes/Source.recordType-meta.xml
<RecordType>
    <fullName>Source</fullName>
    <active>true</active>
    <label>Source</label>
</RecordType>

force-app/main/default/objects/Course_Bucket__c/Course_Bucket__c.object-meta.xml
<CustomObject>
    <label>Course Bucket</label>
    <nameField>
        <label>Course Bucket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Bucket</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/Coming_From__c.field-meta.xml
<CustomField>
    <fullName>Coming_From__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Course</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Course_Bucket__c.field-meta.xml
<CustomField>
    <fullName>Course_Bucket__c</fullName>
    <label>Course Bucket</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Bucket</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Source_Bucket__c.field-meta.xml
<CustomField>
    <fullName>Source_Bucket__c</fullName>
    <formula>IF(
    ISPICKVAL( Coming_From__c, &quot;Facebook&quot;) ||
    ISPICKVAL(Coming_From__c, &quot;Advertisement&quot;) ||
    ISPICKVAL(Coming_From__c, &quot;website-contact_us&quot;) ||
    ISPICKVAL(Coming_From__c, &quot;Google Ads&quot;),
    &quot;Bucket 1&quot;,

IF(
    ISPICKVAL(Coming_From__c, &quot;Website&quot;) ||
    ISPICKVAL(Coming_From__c, &quot;Landing Page&quot;),
    &quot;Bucket 2&quot;,

IF(
    ISPICKVAL(Coming_From__c, &quot;Referral&quot;) ||
    ISPICKVAL(Coming_From__c, &quot;Partner&quot;),
    &quot;Bucket 3&quot;,

&quot;Bucket 4&quot;
)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Source Bucket</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Source_Bucket__c/Source_Bucket__c.object-meta.xml
<CustomObject>
    <label>Source Bucket</label>
    <nameField>
        <label>Source Bucket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Source Buckets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Source_Bucket__c/fields/source__c.field-meta.xml
<CustomField>
    <fullName>source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Bucket.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bucket 1</fullName>
    </customValue>
    <customValue>
        <fullName>Bucket 2</fullName>
    </customValue>
    <customValue>
        <fullName>Bucket 3</fullName>
    </customValue>
    <customValue>
        <fullName>Bucket 4</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
    </customValue>
    <masterLabel>Bucket</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Course.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CMA</fullName>
    </customValue>
    <customValue>
        <fullName>CPA</fullName>
    </customValue>
    <customValue>
        <fullName>CAIRA</fullName>
    </customValue>
    <customValue>
        <fullName>MCOM</fullName>
    </customValue>
    <customValue>
        <fullName>US Pathway</fullName>
    </customValue>
    <masterLabel>Course</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Facebook</fullName>
    </customValue>
    <customValue>
        <fullName>Advertisement</fullName>
    </customValue>
    <customValue>
        <fullName>website-contact_us</fullName>
    </customValue>
    <customValue>
        <fullName>Website</fullName>
    </customValue>
    <customValue>
        <fullName>Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Google Ads</fullName>
    </customValue>
    <customValue>
        <fullName>IVR</fullName>
    </customValue>
    <customValue>
        <fullName>Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Whatsapp Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>WhatsApp BOT on Website</fullName>
    </customValue>
    <customValue>
        <fullName>Live Chat on Website</fullName>
    </customValue>
    <customValue>
        <fullName>SuperBot</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook Ads</fullName>
    </customValue>
    <customValue>
        <fullName>Email Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Miles One App</fullName>
    </customValue>
    <customValue>
        <fullName>Referral - Manual</fullName>
    </customValue>
    <customValue>
        <fullName>Zoom Webinar</fullName>
    </customValue>
    <customValue>
        <fullName>Social</fullName>
    </customValue>
    <customValue>
        <fullName>TimesInternet</fullName>
    </customValue>
    <customValue>
        <fullName>SMS Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Newsletter Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Youtube</fullName>
    </customValue>
    <customValue>
        <fullName>Live Chat</fullName>
    </customValue>
    <customValue>
        <fullName>Incoming Call</fullName>
    </customValue>
    <customValue>
        <fullName>Instagram</fullName>
    </customValue>
    <customValue>
        <fullName>CA-DB</fullName>
    </customValue>
    <customValue>
        <fullName>Blog Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Times Jobs</fullName>
    </customValue>
    <customValue>
        <fullName>Placement Drive</fullName>
    </customValue>
    <customValue>
        <fullName>Naukri</fullName>
    </customValue>
    <masterLabel>Source</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BucketAssignmentServiceTest.cls
@isTest
public class BucketAssignmentServiceTest {
    
    @isTest
    static void testAssignBucketInsert() {
        insert new Bucket_Mapping__c(
            Bucket__c = 'Bucket 1',
            Value_Type__c = 'Course',
            Active__c = true,
            Sequence__c = 1,
            Course_Values__c = 'CPA;CMA'
        );
        insert new Bucket_Mapping__c(
            Bucket__c = 'Bucket 2',
            Value_Type__c = 'Source',
            Active__c = true,
            Sequence__c = 1,
            Source_Values__c = 'Blog Makreting;CA-DB'
        );

        Lead l = new Lead(
            LastName = 'TestLead',
            Company = 'TestCompany'
        );
        
        // Use real values found in the org metadata for better coverage
        try {
            l.put('Course__c', 'CPA');
            l.put('Source__c', 'Blog Makreting');
        } catch (Exception e) {}

        List<SObject> newList = new List<SObject>{l};
        
        Test.startTest();
        BucketAssignmentService.assignBucket(newList, null);
        Test.stopTest();
        
        System.assertNotEquals(null, l);
        System.assertEquals('Bucket 1', (String)l.get('Course_Bucket__c'));
        System.assertEquals('Bucket 2', (String)l.get('Source_Bucket__c'));
    }

    @isTest
    static void testAssignBucketUpdate() {
        insert new Bucket_Mapping__c(
            Bucket__c = 'Bucket 1',
            Value_Type__c = 'Course',
            Active__c = true,
            Sequence__c = 1,
            Course_Values__c = 'CMA'
        );
        insert new Bucket_Mapping__c(
            Bucket__c = 'Bucket 2',
            Value_Type__c = 'Source',
            Active__c = true,
            Sequence__c = 1,
            Source_Values__c = 'CA-DB'
        );

        Lead oldL = TestDataFactory.createLead('Old', 'Company', 'Open');
        Lead newL = oldL.clone(true, true, true, true);
        
        try {
            newL.put('Course__c', 'CMA');
            newL.put('Coming_From__c', 'CA-DB');
        } catch (Exception e) {}

        Map<Id, SObject> oldMap = new Map<Id, SObject>{oldL.Id => oldL};
        List<SObject> newList = new List<SObject>{newL};

        Test.startTest();
        BucketAssignmentService.assignBucket(newList, oldMap);
        Test.stopTest();
        
        System.assertNotEquals(null, newList);
        System.assertEquals('Bucket 1', (String)newL.get('Course_Bucket__c'));
        System.assertEquals('Bucket 2', (String)newL.get('Source_Bucket__c'));
    }

    @isTest
    static void testEmptyList() {
        BucketAssignmentService.assignBucket(new List<SObject>(), null);
    }
}