force-app/main/default/objects/Course_Bucket__c/Course_Bucket__c.object-meta.xml
<CustomObject>
    <label>Course Bucket</label>
    <nameField>
        <label>Course Bucket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Bucket</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Course</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Course_Bucket__c.field-meta.xml
<CustomField>
    <fullName>Course_Bucket__c</fullName>
    <label>Course Bucket</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Bucket</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Is_Merged__c.field-meta.xml
<CustomField>
    <fullName>Is_Merged__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Merged</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Source_Bucket__c.field-meta.xml
<CustomField>
    <fullName>Source_Bucket__c</fullName>
    <formula>IF(
    ISPICKVAL( Coming_From__c, &quot;Facebook&quot;) ||
    ISPICKVAL(Coming_From__c, &quot;Advertisement&quot;) ||
    ISPICKVAL(Coming_From__c, &quot;website-contact_us&quot;) ||
    ISPICKVAL(Coming_From__c, &quot;Google Ads&quot;),
    &quot;Bucket 1&quot;,

IF(
    ISPICKVAL(Coming_From__c, &quot;Website&quot;) ||
    ISPICKVAL(Coming_From__c, &quot;Landing Page&quot;),
    &quot;Bucket 2&quot;,

IF(
    ISPICKVAL(Coming_From__c, &quot;Referral&quot;) ||
    ISPICKVAL(Coming_From__c, &quot;Partner&quot;),
    &quot;Bucket 3&quot;,

&quot;Bucket 4&quot;
)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Source Bucket</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/CAN_ID__c.field-meta.xml
<CustomField>
    <fullName>CAN_ID__c</fullName>
    <formula>Candidate__r.Candidate_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CAN ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/CC_Spoc__c.field-meta.xml
<CustomField>
    <fullName>CC_Spoc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CC Spoc</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Course</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Course_Bucket__c.field-meta.xml
<CustomField>
    <fullName>Course_Bucket__c</fullName>
    <label>Course Bucket</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Bucket</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Expected_payment_date__c.field-meta.xml
<CustomField>
    <fullName>Expected_payment_date__c</fullName>
    <label>Expected payment date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/GP_SPOC__c.field-meta.xml
<CustomField>
    <fullName>GP_SPOC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GP SPOC</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Is_Merged__c.field-meta.xml
<CustomField>
    <fullName>Is_Merged__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Merged</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Is_ReEnquiry__c.field-meta.xml
<CustomField>
    <fullName>Is_ReEnquiry__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is ReEnquiry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead_Merge_Comments__c.field-meta.xml
<CustomField>
    <fullName>Lead_Merge_Comments__c</fullName>
    <label>Lead Merge Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Not_Commited__c.field-meta.xml
<CustomField>
    <fullName>Not_Commited__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Not Commited</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Payment_Received__c.field-meta.xml
<CustomField>
    <fullName>Payment_Received__c</fullName>
    <label>Payment Received</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fully Received</fullName>
            </value>
            <value>
                <fullName>Partially Received</fullName>
            </value>
            <value>
                <fullName>Not Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Source_Bucket__c.field-meta.xml
<CustomField>
    <fullName>Source_Bucket__c</fullName>
    <label>Source Bucket</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Bucket</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>M_Stages</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Source_Bucket__c/Source_Bucket__c.object-meta.xml
<CustomObject>
    <label>Source Bucket</label>
    <nameField>
        <label>Source Bucket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Source Buckets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Source_Bucket__c/fields/source__c.field-meta.xml
<CustomField>
    <fullName>source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Bucket.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bucket 1</fullName>
    </customValue>
    <customValue>
        <fullName>Bucket 2</fullName>
    </customValue>
    <customValue>
        <fullName>Bucket 3</fullName>
    </customValue>
    <customValue>
        <fullName>Bucket 4</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
    </customValue>
    <masterLabel>Bucket</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Course.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CMA</fullName>
    </customValue>
    <customValue>
        <fullName>CPA</fullName>
    </customValue>
    <customValue>
        <fullName>CAIRA</fullName>
    </customValue>
    <customValue>
        <fullName>MCOM</fullName>
    </customValue>
    <customValue>
        <fullName>US Pathway</fullName>
    </customValue>
    <masterLabel>Course</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/M_Stages.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>M1</fullName>
    </customValue>
    <customValue>
        <fullName>M2</fullName>
    </customValue>
    <customValue>
        <fullName>M3</fullName>
    </customValue>
    <customValue>
        <fullName>M3+</fullName>
    </customValue>
    <customValue>
        <fullName>M3++</fullName>
    </customValue>
    <customValue>
        <fullName>M4-</fullName>
    </customValue>
    <customValue>
        <fullName>M4</fullName>
    </customValue>
    <customValue>
        <fullName>M5</fullName>
    </customValue>
    <customValue>
        <fullName>M6</fullName>
    </customValue>
    <customValue>
        <fullName>M7</fullName>
    </customValue>
    <customValue>
        <fullName>M7+</fullName>
    </customValue>
    <customValue>
        <fullName>B1</fullName>
    </customValue>
    <customValue>
        <fullName>B2</fullName>
    </customValue>
    <customValue>
        <fullName>B3</fullName>
    </customValue>
    <customValue>
        <fullName>B3+</fullName>
    </customValue>
    <customValue>
        <fullName>B3++</fullName>
    </customValue>
    <customValue>
        <fullName>B4-</fullName>
    </customValue>
    <customValue>
        <fullName>B4</fullName>
    </customValue>
    <customValue>
        <fullName>B5</fullName>
    </customValue>
    <customValue>
        <fullName>B6</fullName>
    </customValue>
    <customValue>
        <fullName>B7</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
    </customValue>
    <customValue>
        <fullName>M7#</fullName>
    </customValue>
    <customValue>
        <fullName>U1</fullName>
    </customValue>
    <customValue>
        <fullName>U2</fullName>
    </customValue>
    <customValue>
        <fullName>U3</fullName>
    </customValue>
    <customValue>
        <fullName>U3+</fullName>
    </customValue>
    <customValue>
        <fullName>U3++</fullName>
    </customValue>
    <customValue>
        <fullName>U4-</fullName>
    </customValue>
    <customValue>
        <fullName>U4</fullName>
    </customValue>
    <masterLabel>M Stages</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Facebook</fullName>
    </customValue>
    <customValue>
        <fullName>Advertisement</fullName>
    </customValue>
    <customValue>
        <fullName>website-contact_us</fullName>
    </customValue>
    <customValue>
        <fullName>Website</fullName>
    </customValue>
    <customValue>
        <fullName>Referral</fullName>
    </customValue>
    <customValue>
        <fullName>Google Ads</fullName>
    </customValue>
    <customValue>
        <fullName>IVR</fullName>
    </customValue>
    <customValue>
        <fullName>Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Whatsapp Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>WhatsApp BOT on Website</fullName>
    </customValue>
    <customValue>
        <fullName>Live Chat on Website</fullName>
    </customValue>
    <customValue>
        <fullName>SuperBot</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook Ads</fullName>
    </customValue>
    <customValue>
        <fullName>Email Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Miles One App</fullName>
    </customValue>
    <customValue>
        <fullName>Referral - Manual</fullName>
    </customValue>
    <customValue>
        <fullName>Zoom Webinar</fullName>
    </customValue>
    <customValue>
        <fullName>Social</fullName>
    </customValue>
    <customValue>
        <fullName>TimesInternet</fullName>
    </customValue>
    <customValue>
        <fullName>SMS Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Newsletter Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Youtube</fullName>
    </customValue>
    <customValue>
        <fullName>Live Chat</fullName>
    </customValue>
    <customValue>
        <fullName>Incoming Call</fullName>
    </customValue>
    <customValue>
        <fullName>Instagram</fullName>
    </customValue>
    <customValue>
        <fullName>CA-DB</fullName>
    </customValue>
    <customValue>
        <fullName>Blog Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Times Jobs</fullName>
    </customValue>
    <customValue>
        <fullName>Placement Drive</fullName>
    </customValue>
    <customValue>
        <fullName>Naukri</fullName>
    </customValue>
    <masterLabel>Source</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProcessInstanceLeadService.cls
public with sharing class ProcessInstanceLeadService {
    @AuraEnabled(cacheable=true)
    public static LeadMergeWrapper getLeadForWorkitem(Id workitemId) {
        if (workitemId == null) return null;

        ProcessInstanceWorkitem wi = [
            SELECT Id, ProcessInstance.TargetObjectId
            FROM ProcessInstanceWorkitem
            WHERE Id = :workitemId
            LIMIT 1
        ];

        Id targetId = wi.ProcessInstance.TargetObjectId;
        if (targetId == null || targetId.getSObjectType() != Lead__c.SObjectType) return null;

        Lead__c mainLead = [
            SELECT Id, Name, Stage__c, CAN_ID__c, City__c, Course__c, Course_Bucket__c,
                   Source__c, Source_Bucket__c, Candidate__c, Student__c, OwnerId,
                   Is_ReEnquiry__c, Is_Merged__c, Expected_payment_date__c, Payment_Received__c,
                   Status__c, CC_Spoc__c, GP_SPOC__c, Not_Commited__c, Lead_Merge_Comments__c
            FROM Lead__c
            WHERE Id = :targetId
            LIMIT 1
        ];

        // Fetch the lead being merged (Child lead where Lead__c = mainLead.Id)
        List<Lead__c> mergedLeads = [
            SELECT Id, Name, Stage__c, CAN_ID__c, City__c, Course__c, Course_Bucket__c,
                   Source__c, Source_Bucket__c, Candidate__c, Student__c, OwnerId,
                   Is_ReEnquiry__c, Is_Merged__c, Expected_payment_date__c, Payment_Received__c,
                   Status__c, CC_Spoc__c, GP_SPOC__c, Not_Commited__c
            FROM Lead__c
            WHERE Lead__c = :targetId
            ORDER BY CreatedDate DESC
            LIMIT 1
        ];

        LeadMergeWrapper wrapper = new LeadMergeWrapper();
        wrapper.mainLead = mainLead;
        if (!mergedLeads.isEmpty()) {
            wrapper.mergedLead = mergedLeads[0];
        }
        return wrapper;
    }

    public class LeadMergeWrapper {
        @AuraEnabled public Lead__c mainLead;
        @AuraEnabled public Lead__c mergedLead;
    }
}